# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/trace/consensus_service.proto

require 'google/protobuf'


descriptor_data = "\n*block/stream/trace/consensus_service.proto\x12\"com.hedera.hapi.block.stream.trace\"G\n\x16SubmitMessageTraceData\x12\x17\n\x0fsequence_number\x18\x01 \x01(\x03\x12\x14\n\x0crunning_hash\x18\x02 \x01(\x0c\x42-\n)com.hedera.hapi.block.stream.trace.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          module Trace
            SubmitMessageTraceData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.trace.SubmitMessageTraceData").msgclass
          end
        end
      end
    end
  end
end
