# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/trace/smart_contract_service.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/streams/contract_action_pb'


descriptor_data = "\n/block/stream/trace/smart_contract_service.proto\x12\"com.hedera.hapi.block.stream.trace\x1a\x1aservices/basic_types.proto\x1a\x1dstreams/contract_action.proto\"\xcd\x01\n\x11\x43ontractSlotUsage\x12&\n\x0b\x63ontract_id\x18\x01 \x01(\x0b\x32\x11.proto.ContractID\x12N\n\x11written_slot_keys\x18\x03 \x01(\x0b\x32\x33.com.hedera.hapi.block.stream.trace.WrittenSlotKeys\x12@\n\nslot_reads\x18\x04 \x03(\x0b\x32,.com.hedera.hapi.block.stream.trace.SlotRead\"\x1f\n\x0fWrittenSlotKeys\x12\x0c\n\x04keys\x18\x01 \x03(\x0c\"L\n\x08SlotRead\x12\x0f\n\x05index\x18\x01 \x01(\x05H\x00\x12\r\n\x03key\x18\x02 \x01(\x0cH\x00\x12\x12\n\nread_value\x18\x03 \x01(\x0c\x42\x0c\n\nidentifier\"\xb6\x01\n\x10\x45xecutedInitcode\x12&\n\x0b\x63ontract_id\x18\x01 \x01(\x0b\x32\x11.proto.ContractID\x12Q\n\x11initcode_bookends\x18\x02 \x01(\x0b\x32\x34.com.hedera.hapi.block.stream.trace.InitcodeBookendsH\x00\x12\x1b\n\x11\x65xplicit_initcode\x18\x03 \x01(\x0cH\x00\x42\n\n\x08initcode\"F\n\x10InitcodeBookends\x12\x17\n\x0f\x64\x65ploy_bytecode\x18\x01 \x01(\x0c\x12\x19\n\x11metadata_bytecode\x18\x02 \x01(\x0c\"Y\n\x11\x45vmTransactionLog\x12&\n\x0b\x63ontract_id\x18\x01 \x01(\x0b\x32\x11.proto.ContractID\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0e\n\x06topics\x18\x03 \x03(\x0c\"\xc1\x02\n\x0c\x45vmTraceData\x12/\n\x10\x63ontract_actions\x18\x01 \x03(\x0b\x32\x15.proto.ContractAction\x12S\n\x14\x63ontract_slot_usages\x18\x02 \x03(\x0b\x32\x35.com.hedera.hapi.block.stream.trace.ContractSlotUsage\x12\x15\n\rerror_details\x18\x03 \x01(\t\x12O\n\x11\x65xecuted_initcode\x18\x04 \x01(\x0b\x32\x34.com.hedera.hapi.block.stream.trace.ExecutedInitcode\x12\x43\n\x04logs\x18\x05 \x03(\x0b\x32\x35.com.hedera.hapi.block.stream.trace.EvmTransactionLogB-\n)com.hedera.hapi.block.stream.trace.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          module Trace
            ContractSlotUsage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.trace.ContractSlotUsage").msgclass
            WrittenSlotKeys = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.trace.WrittenSlotKeys").msgclass
            SlotRead = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.trace.SlotRead").msgclass
            ExecutedInitcode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.trace.ExecutedInitcode").msgclass
            InitcodeBookends = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.trace.InitcodeBookends").msgclass
            EvmTransactionLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.trace.EvmTransactionLog").msgclass
            EvmTraceData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.trace.EvmTraceData").msgclass
          end
        end
      end
    end
  end
end
