# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/trace/trace_data.proto

require 'google/protobuf'

require 'hiero/proto/block/stream/trace/smart_contract_service_pb'
require 'hiero/proto/block/stream/trace/consensus_service_pb'


descriptor_data = "\n#block/stream/trace/trace_data.proto\x12\"com.hedera.hapi.block.stream.trace\x1a/block/stream/trace/smart_contract_service.proto\x1a*block/stream/trace/consensus_service.proto\"\xc0\x01\n\tTraceData\x12J\n\x0e\x65vm_trace_data\x18\x01 \x01(\x0b\x32\x30.com.hedera.hapi.block.stream.trace.EvmTraceDataH\x00\x12_\n\x19submit_message_trace_data\x18\x02 \x01(\x0b\x32:.com.hedera.hapi.block.stream.trace.SubmitMessageTraceDataH\x00\x42\x06\n\x04\x64\x61taB-\n)com.hedera.hapi.block.stream.trace.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          module Trace
            TraceData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.trace.TraceData").msgclass
          end
        end
      end
    end
  end
end
