# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/auxiliary/tss/ledger_id_publication.proto

require 'google/protobuf'


descriptor_data = "\n2services/auxiliary/tss/ledger_id_publication.proto\x12\x18\x63om.hedera.hapi.node.tss\"\xaf\x01\n\"LedgerIdPublicationTransactionBody\x12\x11\n\tledger_id\x18\x01 \x01(\x0c\x12&\n\x1ehistory_proof_verification_key\x18\x02 \x01(\x0c\x12N\n\x12node_contributions\x18\x03 \x03(\x0b\x32\x32.com.hedera.hapi.node.tss.LedgerIdNodeContribution\"V\n\x18LedgerIdNodeContribution\x12\x0f\n\x07node_id\x18\x01 \x01(\x04\x12\x0e\n\x06weight\x18\x02 \x01(\x04\x12\x19\n\x11history_proof_key\x18\x03 \x01(\x0c\x42#\n\x1f\x63om.hedera.hapi.node.tss.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module Tss
          LedgerIdPublicationTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.tss.LedgerIdPublicationTransactionBody").msgclass
          LedgerIdNodeContribution = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.tss.LedgerIdNodeContribution").msgclass
        end
      end
    end
  end
end
