# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/auxiliary/tss/tss_vote.proto

require 'google/protobuf'


descriptor_data = "\n%services/auxiliary/tss/tss_vote.proto\x12&com.hedera.hapi.services.auxiliary.tss\"\x8d\x01\n\x16TssVoteTransactionBody\x12\x1a\n\x12source_roster_hash\x18\x01 \x01(\x0c\x12\x1a\n\x12target_roster_hash\x18\x02 \x01(\x0c\x12\x11\n\tledger_id\x18\x03 \x01(\x0c\x12\x16\n\x0enode_signature\x18\x04 \x01(\x0c\x12\x10\n\x08tss_vote\x18\x05 \x01(\x0c\x42\x31\n-com.hedera.hapi.services.auxiliary.tss.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Services
        module Auxiliary
          module Tss
            TssVoteTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.services.auxiliary.tss.TssVoteTransactionBody").msgclass
          end
        end
      end
    end
  end
end
