# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/auxiliary/tss/tss_encryption_key.proto

require 'google/protobuf'


descriptor_data = "\n/services/auxiliary/tss/tss_encryption_key.proto\x12&com.hedera.hapi.services.auxiliary.tss\"A\n\x1fTssEncryptionKeyTransactionBody\x12\x1e\n\x16publicTssEncryptionKey\x18\x01 \x01(\x0c\x42\x31\n-com.hedera.hapi.services.auxiliary.tss.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Services
        module Auxiliary
          module Tss
            TssEncryptionKeyTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.services.auxiliary.tss.TssEncryptionKeyTransactionBody").msgclass
          end
        end
      end
    end
  end
end
