# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/auxiliary/tss/tss_message.proto

require 'google/protobuf'


descriptor_data = "\n(services/auxiliary/tss/tss_message.proto\x12&com.hedera.hapi.services.auxiliary.tss\"}\n\x19TssMessageTransactionBody\x12\x1a\n\x12source_roster_hash\x18\x01 \x01(\x0c\x12\x1a\n\x12target_roster_hash\x18\x02 \x01(\x0c\x12\x13\n\x0bshare_index\x18\x03 \x01(\x04\x12\x13\n\x0btss_message\x18\x04 \x01(\x0c\x42\x31\n-com.hedera.hapi.services.auxiliary.tss.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Services
        module Auxiliary
          module Tss
            TssMessageTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.services.auxiliary.tss.TssMessageTransactionBody").msgclass
          end
        end
      end
    end
  end
end
