# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/contract/bytecode.proto

require 'google/protobuf'


descriptor_data = "\n&services/state/contract/bytecode.proto\x12\x05proto\"\x18\n\x08\x42ytecode\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x0c\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  Bytecode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Bytecode").msgclass
end
