# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/contract/evm_hook_state.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/hook_types_pb'
require 'google/protobuf/wrappers_pb'


descriptor_data = "\n,services/state/contract/evm_hook_state.proto\x12 com.hedera.hapi.node.state.hooks\x1a\x1aservices/basic_types.proto\x1a\x19services/hook_types.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xa6\x03\n\x0c\x45vmHookState\x12\x1e\n\x07hook_id\x18\x01 \x01(\x0b\x32\r.proto.HookId\x12\x38\n\x04type\x18\x02 \x01(\x0e\x32*.com.hedera.hapi.node.state.hooks.HookType\x12G\n\x0f\x65xtension_point\x18\x03 \x01(\x0e\x32..com.hedera.hapi.node.hooks.HookExtensionPoint\x12+\n\x10hook_contract_id\x18\x04 \x01(\x0b\x32\x11.proto.ContractID\x12\x1d\n\tadmin_key\x18\x05 \x01(\x0b\x32\n.proto.Key\x12\"\n\x1a\x66irst_contract_storage_key\x18\x06 \x01(\x0c\x12\x35\n\x10previous_hook_id\x18\x07 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12\x31\n\x0cnext_hook_id\x18\x08 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12\x19\n\x11num_storage_slots\x18\t \x01(\r\"=\n\x0e\x45vmHookSlotKey\x12\x1e\n\x07hook_id\x18\x01 \x01(\x0b\x32\r.proto.HookId\x12\x0b\n\x03key\x18\x02 \x01(\x0c*\x18\n\x08HookType\x12\x0c\n\x08\x45VM_HOOK\x10\x00\x42+\n\'com.hedera.hapi.node.state.hooks.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module State
          module Hooks
            EvmHookState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.hooks.EvmHookState").msgclass
            EvmHookSlotKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.hooks.EvmHookSlotKey").msgclass
            HookType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.hooks.HookType").enummodule
          end
        end
      end
    end
  end
end
