# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/contract/storage_slot.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n*services/state/contract/storage_slot.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"=\n\x07SlotKey\x12%\n\ncontractID\x18\x01 \x01(\x0b\x32\x11.proto.ContractID\x12\x0b\n\x03key\x18\x02 \x01(\x0c\"B\n\tSlotValue\x12\r\n\x05value\x18\x01 \x01(\x0c\x12\x14\n\x0cprevious_key\x18\x02 \x01(\x0c\x12\x10\n\x08next_key\x18\x03 \x01(\x0c\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  SlotKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SlotKey").msgclass
  SlotValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SlotValue").msgclass
end
