# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/consensus/topic.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/custom_fees_pb'


descriptor_data = "\n$services/state/consensus/topic.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1aservices/custom_fees.proto\"\x98\x03\n\x05Topic\x12 \n\x08topic_id\x18\x01 \x01(\x0b\x32\x0e.proto.TopicID\x12\x17\n\x0fsequence_number\x18\x02 \x01(\x03\x12\x19\n\x11\x65xpiration_second\x18\x03 \x01(\x03\x12\x19\n\x11\x61uto_renew_period\x18\x04 \x01(\x03\x12/\n\x15\x61uto_renew_account_id\x18\x05 \x01(\x0b\x32\x10.proto.AccountID\x12\x0f\n\x07\x64\x65leted\x18\x06 \x01(\x08\x12\x14\n\x0crunning_hash\x18\x07 \x01(\x0c\x12\x0c\n\x04memo\x18\x08 \x01(\t\x12\x1d\n\tadmin_key\x18\t \x01(\x0b\x32\n.proto.Key\x12\x1e\n\nsubmit_key\x18\n \x01(\x0b\x32\n.proto.Key\x12$\n\x10\x66\x65\x65_schedule_key\x18\x0b \x01(\x0b\x32\n.proto.Key\x12\'\n\x13\x66\x65\x65_exempt_key_list\x18\x0c \x03(\x0b\x32\n.proto.Key\x12*\n\x0b\x63ustom_fees\x18\r \x03(\x0b\x32\x15.proto.FixedCustomFeeB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  Topic = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Topic").msgclass
end
