# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/input/event_metadata.proto

require 'google/protobuf'

require 'hiero/proto/platform/event/event_core_pb'
require 'hiero/proto/platform/event/event_descriptor_pb'


descriptor_data = "\n\'block/stream/input/event_metadata.proto\x12\"com.hedera.hapi.block.stream.input\x1a\x1fplatform/event/event_core.proto\x1a%platform/event/event_descriptor.proto\"\x97\x01\n\x0b\x45ventHeader\x12=\n\nevent_core\x18\x01 \x01(\x0b\x32).com.hedera.hapi.platform.event.EventCore\x12I\n\x07parents\x18\x02 \x03(\x0b\x32\x38.com.hedera.hapi.block.stream.input.ParentEventReference\"~\n\x14ParentEventReference\x12K\n\x10\x65vent_descriptor\x18\x01 \x01(\x0b\x32/.com.hedera.hapi.platform.event.EventDescriptorH\x00\x12\x0f\n\x05index\x18\x02 \x01(\rH\x00\x42\x08\n\x06parentB-\n)com.hedera.hapi.block.stream.input.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          module Input
            EventHeader = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.input.EventHeader").msgclass
            ParentEventReference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.input.ParentEventReference").msgclass
          end
        end
      end
    end
  end
end
