# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/input/round_header.proto

require 'google/protobuf'


descriptor_data = "\n%block/stream/input/round_header.proto\x12\"com.hedera.hapi.block.stream.input\"#\n\x0bRoundHeader\x12\x14\n\x0cround_number\x18\x01 \x01(\x04\x42-\n)com.hedera.hapi.block.stream.input.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          module Input
            RoundHeader = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.input.RoundHeader").msgclass
          end
        end
      end
    end
  end
end
