# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/auxiliary/blockrecords/migration_root_hash_vote.proto

require 'google/protobuf'


descriptor_data = "\n>services/auxiliary/blockrecords/migration_root_hash_vote.proto\x12/com.hedera.hapi.services.auxiliary.blockrecords\"\xc5\x01\n$MigrationRootHashVoteTransactionBody\x12/\n\'previous_wrapped_record_block_root_hash\x18\x01 \x01(\x0c\x12\x37\n/wrapped_intermediate_previous_block_root_hashes\x18\x02 \x03(\x0c\x12\x33\n+wrapped_intermediate_block_roots_leaf_count\x18\x03 \x01(\x04\x42:\n6com.hedera.hapi.services.auxiliary.blockrecords.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Services
        module Auxiliary
          module Blockrecords
            MigrationRootHashVoteTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.services.auxiliary.blockrecords.MigrationRootHashVoteTransactionBody").msgclass
          end
        end
      end
    end
  end
end
