# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/schedule/schedule.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/timestamp_pb'
require 'hiero/proto/services/schedulable_transaction_body_pb'
require 'hiero/proto/services/transaction_pb'


descriptor_data = "\n&services/state/schedule/schedule.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x18services/timestamp.proto\x1a+services/schedulable_transaction_body.proto\x1a\x1aservices/transaction.proto\"\xbc\x04\n\x08Schedule\x12&\n\x0bschedule_id\x18\x01 \x01(\x0b\x32\x11.proto.ScheduleID\x12\x0f\n\x07\x64\x65leted\x18\x02 \x01(\x08\x12\x10\n\x08\x65xecuted\x18\x03 \x01(\x08\x12\x17\n\x0fwait_for_expiry\x18\x04 \x01(\x08\x12\x0c\n\x04memo\x18\x05 \x01(\t\x12.\n\x14scheduler_account_id\x18\x06 \x01(\x0b\x32\x10.proto.AccountID\x12*\n\x10payer_account_id\x18\x07 \x01(\x0b\x32\x10.proto.AccountID\x12\x1d\n\tadmin_key\x18\x08 \x01(\x0b\x32\n.proto.Key\x12.\n\x14schedule_valid_start\x18\t \x01(\x0b\x32\x10.proto.Timestamp\x12\"\n\x1aprovided_expiration_second\x18\n \x01(\x03\x12$\n\x1c\x63\x61lculated_expiration_second\x18\x0b \x01(\x03\x12)\n\x0fresolution_time\x18\x0c \x01(\x0b\x32\x10.proto.Timestamp\x12@\n\x15scheduled_transaction\x18\r \x01(\x0b\x32!.proto.SchedulableTransactionBody\x12;\n\x1boriginal_create_transaction\x18\x0e \x01(\x0b\x32\x16.proto.TransactionBody\x12\x1f\n\x0bsignatories\x18\x0f \x03(\x0b\x32\n.proto.Key\"2\n\x0cScheduleList\x12\"\n\tschedules\x18\x01 \x03(\x0b\x32\x0f.proto.Schedule\"9\n\x0eScheduleIdList\x12\'\n\x0cschedule_ids\x18\x01 \x03(\x0b\x32\x11.proto.ScheduleID\"E\n\x0fScheduledCounts\x12\x18\n\x10number_scheduled\x18\x01 \x01(\r\x12\x18\n\x10number_processed\x18\x02 \x01(\r\"=\n\x0eScheduledOrder\x12\x15\n\rexpiry_second\x18\x01 \x01(\x04\x12\x14\n\x0corder_number\x18\x02 \x01(\rB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  Schedule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Schedule").msgclass
  ScheduleList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ScheduleList").msgclass
  ScheduleIdList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ScheduleIdList").msgclass
  ScheduledCounts = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ScheduledCounts").msgclass
  ScheduledOrder = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ScheduledOrder").msgclass
end
