# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams/account_balance_file.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/timestamp_pb'


descriptor_data = "\n\"streams/account_balance_file.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x18services/timestamp.proto\"D\n\x10TokenUnitBalance\x12\x1f\n\x07tokenId\x18\x01 \x01(\x0b\x32\x0e.proto.TokenID\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x04\"\x85\x01\n\x15SingleAccountBalances\x12#\n\taccountID\x18\x01 \x01(\x0b\x32\x10.proto.AccountID\x12\x13\n\x0bhbarBalance\x18\x02 \x01(\x04\x12\x32\n\x11tokenUnitBalances\x18\x03 \x03(\x0b\x32\x17.proto.TokenUnitBalance\"u\n\x12\x41llAccountBalances\x12,\n\x12\x63onsensusTimestamp\x18\x01 \x01(\x0b\x32\x10.proto.Timestamp\x12\x31\n\x0b\x61llAccounts\x18\x02 \x03(\x0b\x32\x1c.proto.SingleAccountBalancesB$\n com.hedera.services.stream.protoP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TokenUnitBalance = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenUnitBalance").msgclass
  SingleAccountBalances = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SingleAccountBalances").msgclass
  AllAccountBalances = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.AllAccountBalances").msgclass
end
