# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams/contract_bytecode.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1fstreams/contract_bytecode.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"f\n\x10\x43ontractBytecode\x12&\n\x0b\x63ontract_id\x18\x01 \x01(\x0b\x32\x11.proto.ContractID\x12\x10\n\x08initcode\x18\x02 \x01(\x0c\x12\x18\n\x10runtime_bytecode\x18\x03 \x01(\x0c\x42$\n com.hedera.services.stream.protoP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ContractBytecode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractBytecode").msgclass
end
