# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams/contract_action.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1dstreams/contract_action.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"B\n\x0f\x43ontractActions\x12/\n\x10\x63ontract_actions\x18\x01 \x03(\x0b\x32\x15.proto.ContractAction\"\x80\x04\n\x0e\x43ontractAction\x12,\n\tcall_type\x18\x01 \x01(\x0e\x32\x19.proto.ContractActionType\x12+\n\x0f\x63\x61lling_account\x18\x02 \x01(\x0b\x32\x10.proto.AccountIDH\x00\x12-\n\x10\x63\x61lling_contract\x18\x03 \x01(\x0b\x32\x11.proto.ContractIDH\x00\x12\x0b\n\x03gas\x18\x04 \x01(\x03\x12\r\n\x05input\x18\x05 \x01(\x0c\x12-\n\x11recipient_account\x18\x06 \x01(\x0b\x32\x10.proto.AccountIDH\x01\x12/\n\x12recipient_contract\x18\x07 \x01(\x0b\x32\x11.proto.ContractIDH\x01\x12\x1a\n\x10targeted_address\x18\x08 \x01(\x0cH\x01\x12\r\n\x05value\x18\t \x01(\x03\x12\x10\n\x08gas_used\x18\n \x01(\x03\x12\x10\n\x06output\x18\x0b \x01(\x0cH\x02\x12\x17\n\rrevert_reason\x18\x0c \x01(\x0cH\x02\x12\x0f\n\x05\x65rror\x18\r \x01(\x0cH\x02\x12\x12\n\ncall_depth\x18\x0e \x01(\x05\x12\x35\n\x13\x63\x61ll_operation_type\x18\x0f \x01(\x0e\x32\x18.proto.CallOperationTypeB\x08\n\x06\x63\x61llerB\x0b\n\trecipientB\r\n\x0bresult_data*U\n\x12\x43ontractActionType\x12\r\n\tNO_ACTION\x10\x00\x12\x08\n\x04\x43\x41LL\x10\x01\x12\n\n\x06\x43REATE\x10\x02\x12\x0e\n\nPRECOMPILE\x10\x03\x12\n\n\x06SYSTEM\x10\x04*\x88\x01\n\x11\x43\x61llOperationType\x12\x0e\n\nOP_UNKNOWN\x10\x00\x12\x0b\n\x07OP_CALL\x10\x01\x12\x0f\n\x0bOP_CALLCODE\x10\x02\x12\x13\n\x0fOP_DELEGATECALL\x10\x03\x12\x11\n\rOP_STATICCALL\x10\x04\x12\r\n\tOP_CREATE\x10\x05\x12\x0e\n\nOP_CREATE2\x10\x06\x42$\n com.hedera.services.stream.protoP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ContractActions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractActions").msgclass
  ContractAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractAction").msgclass
  ContractActionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractActionType").enummodule
  CallOperationType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CallOperationType").enummodule
end
