# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams/contract_state_change.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'google/protobuf/wrappers_pb'


descriptor_data = "\n#streams/contract_state_change.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1egoogle/protobuf/wrappers.proto\"R\n\x14\x43ontractStateChanges\x12:\n\x16\x63ontract_state_changes\x18\x01 \x03(\x0b\x32\x1a.proto.ContractStateChange\"l\n\x13\x43ontractStateChange\x12&\n\x0b\x63ontract_id\x18\x01 \x01(\x0b\x32\x11.proto.ContractID\x12-\n\x0fstorage_changes\x18\x02 \x03(\x0b\x32\x14.proto.StorageChange\"e\n\rStorageChange\x12\x0c\n\x04slot\x18\x01 \x01(\x0c\x12\x12\n\nvalue_read\x18\x02 \x01(\x0c\x12\x32\n\rvalue_written\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.BytesValueB$\n com.hedera.services.stream.protoP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ContractStateChanges = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractStateChanges").msgclass
  ContractStateChange = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractStateChange").msgclass
  StorageChange = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.StorageChange").msgclass
end
