# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams/hash_object.proto

require 'google/protobuf'


descriptor_data = "\n\x19streams/hash_object.proto\x12\x05proto\"S\n\nHashObject\x12\'\n\talgorithm\x18\x01 \x01(\x0e\x32\x14.proto.HashAlgorithm\x12\x0e\n\x06length\x18\x02 \x01(\x05\x12\x0c\n\x04hash\x18\x03 \x01(\x0c*8\n\rHashAlgorithm\x12\x1a\n\x16HASH_ALGORITHM_UNKNOWN\x10\x00\x12\x0b\n\x07SHA_384\x10\x01\x42$\n com.hedera.services.stream.protoP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  HashObject = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.HashObject").msgclass
  HashAlgorithm = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.HashAlgorithm").enummodule
end
