# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams/record_stream_file.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/transaction_pb'
require 'hiero/proto/services/transaction_record_pb'
require 'hiero/proto/streams/hash_object_pb'


descriptor_data = "\n streams/record_stream_file.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1aservices/transaction.proto\x1a!services/transaction_record.proto\x1a\x19streams/hash_object.proto\"\xa6\x02\n\x10RecordStreamFile\x12\x32\n\x12hapi_proto_version\x18\x01 \x01(\x0b\x32\x16.proto.SemanticVersion\x12\x34\n\x19start_object_running_hash\x18\x02 \x01(\x0b\x32\x11.proto.HashObject\x12\x34\n\x13record_stream_items\x18\x03 \x03(\x0b\x32\x17.proto.RecordStreamItem\x12\x32\n\x17\x65nd_object_running_hash\x18\x04 \x01(\x0b\x32\x11.proto.HashObject\x12\x14\n\x0c\x62lock_number\x18\x05 \x01(\x03\x12(\n\x08sidecars\x18\x06 \x03(\x0b\x32\x16.proto.SidecarMetadata\"e\n\x10RecordStreamItem\x12\'\n\x0btransaction\x18\x01 \x01(\x0b\x32\x12.proto.Transaction\x12(\n\x06record\x18\x02 \x01(\x0b\x32\x18.proto.TransactionRecord\"a\n\x0fSidecarMetadata\x12\x1f\n\x04hash\x18\x01 \x01(\x0b\x32\x11.proto.HashObject\x12\n\n\x02id\x18\x02 \x01(\x05\x12!\n\x05types\x18\x03 \x03(\x0e\x32\x12.proto.SidecarType*n\n\x0bSidecarType\x12\x18\n\x14SIDECAR_TYPE_UNKNOWN\x10\x00\x12\x19\n\x15\x43ONTRACT_STATE_CHANGE\x10\x01\x12\x13\n\x0f\x43ONTRACT_ACTION\x10\x02\x12\x15\n\x11\x43ONTRACT_BYTECODE\x10\x03\x42$\n com.hedera.services.stream.protoP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  RecordStreamFile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.RecordStreamFile").msgclass
  RecordStreamItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.RecordStreamItem").msgclass
  SidecarMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SidecarMetadata").msgclass
  SidecarType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SidecarType").enummodule
end
