# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams/sidecar_file.proto

require 'google/protobuf'

require 'hiero/proto/services/timestamp_pb'
require 'hiero/proto/streams/contract_state_change_pb'
require 'hiero/proto/streams/contract_action_pb'
require 'hiero/proto/streams/contract_bytecode_pb'


descriptor_data = "\n\x1astreams/sidecar_file.proto\x12\x05proto\x1a\x18services/timestamp.proto\x1a#streams/contract_state_change.proto\x1a\x1dstreams/contract_action.proto\x1a\x1fstreams/contract_bytecode.proto\"G\n\x0bSidecarFile\x12\x38\n\x0fsidecar_records\x18\x01 \x03(\x0b\x32\x1f.proto.TransactionSidecarRecord\"\xfd\x01\n\x18TransactionSidecarRecord\x12-\n\x13\x63onsensus_timestamp\x18\x01 \x01(\x0b\x32\x10.proto.Timestamp\x12\x11\n\tmigration\x18\x02 \x01(\x08\x12\x34\n\rstate_changes\x18\x03 \x01(\x0b\x32\x1b.proto.ContractStateChangesH\x00\x12)\n\x07\x61\x63tions\x18\x04 \x01(\x0b\x32\x16.proto.ContractActionsH\x00\x12+\n\x08\x62ytecode\x18\x05 \x01(\x0b\x32\x17.proto.ContractBytecodeH\x00\x42\x11\n\x0fsidecar_recordsB$\n com.hedera.services.stream.protoP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  SidecarFile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SidecarFile").msgclass
  TransactionSidecarRecord = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TransactionSidecarRecord").msgclass
end
