# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams/signature_file.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/streams/hash_object_pb'


descriptor_data = "\n\x1cstreams/signature_file.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x19streams/hash_object.proto\"s\n\rSignatureFile\x12.\n\x0e\x66ile_signature\x18\x01 \x01(\x0b\x32\x16.proto.SignatureObject\x12\x32\n\x12metadata_signature\x18\x02 \x01(\x0b\x32\x16.proto.SignatureObject\"\x92\x01\n\x0fSignatureObject\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.proto.SignatureType\x12\x0e\n\x06length\x18\x02 \x01(\x05\x12\x10\n\x08\x63hecksum\x18\x03 \x01(\x05\x12\x11\n\tsignature\x18\x04 \x01(\x0c\x12&\n\x0bhash_object\x18\x05 \x01(\x0b\x32\x11.proto.HashObject*A\n\rSignatureType\x12\x1a\n\x16SIGNATURE_TYPE_UNKNOWN\x10\x00\x12\x14\n\x10SHA_384_WITH_RSA\x10\x01\x42$\n com.hedera.services.stream.protoP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  SignatureFile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SignatureFile").msgclass
  SignatureObject = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SignatureObject").msgclass
  SignatureType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SignatureType").enummodule
end
