# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/common.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1bservices/state/common.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"\"\n\x0c\x45ntityNumber\x12\x0e\n\x06number\x18\x01 \x01(\x03:\x02\x18\x01\"Z\n\x0c\x45ntityIDPair\x12$\n\naccount_id\x18\x01 \x01(\x0b\x32\x10.proto.AccountID\x12 \n\x08token_id\x18\x02 \x01(\x0b\x32\x0e.proto.TokenID:\x02\x18\x01\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  EntityNumber = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.EntityNumber").msgclass
  EntityIDPair = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.EntityIDPair").msgclass
end
