# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/primitives.proto

require 'google/protobuf'


descriptor_data = "\n\x1fservices/state/primitives.proto\x12\x05proto\"\x1a\n\tProtoLong\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1d\n\x0cProtoInteger\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1d\n\x0cProtoBoolean\x12\r\n\x05value\x18\x01 \x01(\x08\"\x1c\n\x0bProtoString\x12\r\n\x05value\x18\x01 \x01(\t\"\x1b\n\nProtoBytes\x12\r\n\x05value\x18\x01 \x01(\x0c\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ProtoLong = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ProtoLong").msgclass
  ProtoInteger = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ProtoInteger").msgclass
  ProtoBoolean = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ProtoBoolean").msgclass
  ProtoString = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ProtoString").msgclass
  ProtoBytes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ProtoBytes").msgclass
end
