# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/throttles/throttle_usage_snapshots.proto

require 'google/protobuf'

require 'hiero/proto/services/timestamp_pb'


descriptor_data = "\n7services/state/throttles/throttle_usage_snapshots.proto\x12\x05proto\x1a\x18services/timestamp.proto\"\xc2\x01\n\x16ThrottleUsageSnapshots\x12\x33\n\rtps_throttles\x18\x01 \x03(\x0b\x32\x1c.proto.ThrottleUsageSnapshot\x12\x32\n\x0cgas_throttle\x18\x02 \x01(\x0b\x32\x1c.proto.ThrottleUsageSnapshot\x12?\n\x19\x65vm_ops_duration_throttle\x18\x03 \x01(\x0b\x32\x1c.proto.ThrottleUsageSnapshot\"S\n\x15ThrottleUsageSnapshot\x12\x0c\n\x04used\x18\x01 \x01(\x03\x12,\n\x12last_decision_time\x18\x02 \x01(\x0b\x32\x10.proto.TimestampB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ThrottleUsageSnapshots = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ThrottleUsageSnapshots").msgclass
  ThrottleUsageSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ThrottleUsageSnapshot").msgclass
end
