# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/state/platform_state.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/timestamp_pb'


descriptor_data = "\n#platform/state/platform_state.proto\x12\x1e\x63om.hedera.hapi.platform.state\x1a\x1aservices/basic_types.proto\x1a\x18services/timestamp.proto\"\x9a\x03\n\rPlatformState\x12\x39\n\x19\x63reation_software_version\x18\x01 \x01(\x0b\x32\x16.proto.SemanticVersion\x12\x1a\n\x12rounds_non_ancient\x18\x02 \x01(\r\x12M\n\x12\x63onsensus_snapshot\x18\x03 \x01(\x0b\x32\x31.com.hedera.hapi.platform.state.ConsensusSnapshot\x12%\n\x0b\x66reeze_time\x18\x04 \x01(\x0b\x32\x10.proto.Timestamp\x12*\n\x10last_frozen_time\x18\x05 \x01(\x0b\x32\x10.proto.Timestamp\x12\x1b\n\x13latest_freeze_round\x18\x06 \x01(\x04\x12&\n\x19legacy_running_event_hash\x18\x90N \x01(\x0c\x42\x02\x18\x01J\x06\x08\x91N\x10\x92NJ\x06\x08\x92N\x10\x93NJ\x06\x08\x93N\x10\x94NJ\x06\x08\x94N\x10\x95NJ\x06\x08\x95N\x10\x96NR\x0c\x61\x64\x64ress_bookR\x15previous_address_book\"\x85\x02\n\x11\x43onsensusSnapshot\x12\r\n\x05round\x18\x01 \x01(\x04\x12Q\n\x17minimum_judge_info_list\x18\x03 \x03(\x0b\x32\x30.com.hedera.hapi.platform.state.MinimumJudgeInfo\x12\x1d\n\x15next_consensus_number\x18\x04 \x01(\x04\x12-\n\x13\x63onsensus_timestamp\x18\x05 \x01(\x0b\x32\x10.proto.Timestamp\x12:\n\tjudge_ids\x18\x06 \x03(\x0b\x32\'.com.hedera.hapi.platform.state.JudgeIdJ\x04\x08\x02\x10\x03\"1\n\x07JudgeId\x12\x12\n\ncreator_id\x18\x01 \x01(\x04\x12\x12\n\njudge_hash\x18\x02 \x01(\x0c\"D\n\x10MinimumJudgeInfo\x12\r\n\x05round\x18\x01 \x01(\x04\x12!\n\x19minimum_judge_birth_round\x18\x02 \x01(\x04\"\x14\n\x06NodeId\x12\n\n\x02id\x18\x01 \x01(\x04\"[\n\x06SigSet\x12Q\n\x14nodeIdSignaturePairs\x18\x01 \x03(\x0b\x32\x33.com.hedera.hapi.platform.state.NodeIdSignaturePair\"T\n\x13NodeIdSignaturePair\x12\x0e\n\x06nodeId\x18\x01 \x01(\x03\x12\x15\n\rsignatureType\x18\x02 \x01(\x05\x12\x16\n\x0esignatureBytes\x18\x03 \x01(\x0c\x42)\n%com.hedera.hapi.platform.state.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Platform
        module State
          PlatformState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.platform.state.PlatformState").msgclass
          ConsensusSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.platform.state.ConsensusSnapshot").msgclass
          JudgeId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.platform.state.JudgeId").msgclass
          MinimumJudgeInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.platform.state.MinimumJudgeInfo").msgclass
          NodeId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.platform.state.NodeId").msgclass
          SigSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.platform.state.SigSet").msgclass
          NodeIdSignaturePair = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.platform.state.NodeIdSignaturePair").msgclass
        end
      end
    end
  end
end
