# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/blockstream/block_stream_info.proto

require 'google/protobuf'

require 'hiero/proto/services/timestamp_pb'
require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n2services/state/blockstream/block_stream_info.proto\x12&com.hedera.hapi.node.state.blockstream\x1a\x18services/timestamp.proto\x1a\x1aservices/basic_types.proto\"\xd5\x05\n\x0f\x42lockStreamInfo\x12\x14\n\x0c\x62lock_number\x18\x01 \x01(\x04\x12$\n\nblock_time\x18\x02 \x01(\x0b\x32\x10.proto.Timestamp\x12\x1e\n\x16trailing_output_hashes\x18\x03 \x01(\x0c\x12\x1d\n\x15trailing_block_hashes\x18\x04 \x01(\x0c\x12\x1c\n\x14input_tree_root_hash\x18\x05 \x01(\x0c\x12!\n\x19start_of_block_state_hash\x18\x06 \x01(\x0c\x12)\n!num_preceding_state_changes_items\x18\x07 \x01(\x04\x12\x35\n-rightmost_preceding_state_changes_tree_hashes\x18\x08 \x03(\x0c\x12(\n\x0e\x62lock_end_time\x18\t \x01(\x0b\x32\x10.proto.Timestamp\x12\x1e\n\x16post_upgrade_work_done\x18\n \x01(\x08\x12\x39\n\x19\x63reation_software_version\x18\x0b \x01(\x0b\x32\x16.proto.SemanticVersion\x12\x34\n\x1alast_interval_process_time\x18\x0c \x01(\x0b\x32\x10.proto.Timestamp\x12*\n\x10last_handle_time\x18\r \x01(\x0b\x32\x10.proto.Timestamp\x12\"\n\x1a\x63onsensus_header_root_hash\x18\x0e \x01(\x0c\x12\x1d\n\x15output_item_root_hash\x18\x0f \x01(\x0c\x12\x1c\n\x14trace_data_root_hash\x18\x10 \x01(\x0c\x12/\n\'intermediate_previous_block_root_hashes\x18\x11 \x03(\x0c\x12+\n#intermediate_block_roots_leaf_count\x18\x12 \x01(\x04\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module State
          module Blockstream
            BlockStreamInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.blockstream.BlockStreamInfo").msgclass
          end
        end
      end
    end
  end
end
