# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/tss/tss_vote_map_key.proto

require 'google/protobuf'


descriptor_data = "\n)services/state/tss/tss_vote_map_key.proto\x12\x1e\x63om.hedera.hapi.node.state.tss\"5\n\rTssVoteMapKey\x12\x13\n\x0broster_hash\x18\x01 \x01(\x0c\x12\x0f\n\x07node_id\x18\x02 \x01(\x04\x42)\n%com.hedera.hapi.node.state.tss.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module State
          module Tss
            TssVoteMapKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.tss.TssVoteMapKey").msgclass
          end
        end
      end
    end
  end
end
