# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/tss/tss_encryption_keys.proto

require 'google/protobuf'


descriptor_data = "\n,services/state/tss/tss_encryption_keys.proto\x12\x1e\x63om.hedera.hapi.node.state.tss\"P\n\x11TssEncryptionKeys\x12\x1e\n\x16\x63urrent_encryption_key\x18\x01 \x01(\x0c\x12\x1b\n\x13next_encryption_key\x18\x02 \x01(\x0c\x42)\n%com.hedera.hapi.node.state.tss.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module State
          module Tss
            TssEncryptionKeys = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.tss.TssEncryptionKeys").msgclass
          end
        end
      end
    end
  end
end
