# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/tss/tss_message_map_key.proto

require 'google/protobuf'


descriptor_data = "\n,services/state/tss/tss_message_map_key.proto\x12\x1e\x63om.hedera.hapi.node.state.tss\"@\n\x10TssMessageMapKey\x12\x13\n\x0broster_hash\x18\x01 \x01(\x0c\x12\x17\n\x0fsequence_number\x18\x02 \x01(\x04\x42)\n%com.hedera.hapi.node.state.tss.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module State
          module Tss
            TssMessageMapKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.tss.TssMessageMapKey").msgclass
          end
        end
      end
    end
  end
end
