# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/blockrecords/block_info.proto

require 'google/protobuf'

require 'hiero/proto/services/timestamp_pb'
require 'hiero/proto/platform/state/platform_state_pb'
require 'hiero/proto/services/auxiliary/blockrecords/migration_root_hash_vote_pb'
require 'hiero/proto/services/state/blockrecords/migration_wrapped_hashes_pb'


descriptor_data = "\n,services/state/blockrecords/block_info.proto\x12\x05proto\x1a\x18services/timestamp.proto\x1a#platform/state/platform_state.proto\x1a>services/auxiliary/blockrecords/migration_root_hash_vote.proto\x1a:services/state/blockrecords/migration_wrapped_hashes.proto\"\xb9\x01\n\x19NodeMigrationRootHashVote\x12\x37\n\x07node_id\x18\x01 \x01(\x0b\x32&.com.hedera.hapi.platform.state.NodeId\x12\x63\n\x04vote\x18\x02 \x01(\x0b\x32U.com.hedera.hapi.services.auxiliary.blockrecords.MigrationRootHashVoteTransactionBody\"\xa8\x06\n\tBlockInfo\x12\x19\n\x11last_block_number\x18\x01 \x01(\x03\x12\x37\n\x1d\x66irst_cons_time_of_last_block\x18\x02 \x01(\x0b\x32\x10.proto.Timestamp\x12\x14\n\x0c\x62lock_hashes\x18\x03 \x01(\x0c\x12\x37\n\x1d\x63ons_time_of_last_handled_txn\x18\x04 \x01(\x0b\x32\x10.proto.Timestamp\x12\"\n\x1amigration_records_streamed\x18\x05 \x01(\x08\x12:\n first_cons_time_of_current_block\x18\x06 \x01(\x0b\x32\x10.proto.Timestamp\x12-\n\x13last_used_cons_time\x18\x07 \x01(\x0b\x32\x10.proto.Timestamp\x12\x34\n\x1alast_interval_process_time\x18\x08 \x01(\x0b\x32\x10.proto.Timestamp\x12/\n\'previous_wrapped_record_block_root_hash\x18\n \x01(\x0c\x12\x37\n/wrapped_intermediate_previous_block_root_hashes\x18\x0b \x03(\x0c\x12\x33\n+wrapped_intermediate_block_roots_leaf_count\x18\x0c \x01(\x04\x12\x17\n\x0fvoting_complete\x18\r \x01(\x08\x12/\n\'voting_completion_deadline_block_number\x18\x0e \x01(\x04\x12\x43\n\x19migration_root_hash_votes\x18\x0f \x03(\x0b\x32 .proto.NodeMigrationRootHashVote\x12\x61\n\x18migration_wrapped_hashes\x18\x10 \x03(\x0b\x32?.com.hedera.hapi.node.state.blockrecords.MigrationWrappedHashes\x12\"\n\x1apreview_stream_overwritten\x18\x11 \x01(\x08\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  NodeMigrationRootHashVote = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NodeMigrationRootHashVote").msgclass
  BlockInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.BlockInfo").msgclass
end
