# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/blockrecords/migration_wrapped_hashes.proto

require 'google/protobuf'


descriptor_data = "\n:services/state/blockrecords/migration_wrapped_hashes.proto\x12\'com.hedera.hapi.node.state.blockrecords\"u\n\x16MigrationWrappedHashes\x12\x14\n\x0c\x62lock_number\x18\x01 \x01(\x04\x12 \n\x18\x63onsensus_timestamp_hash\x18\x02 \x01(\x0c\x12#\n\x1boutput_items_tree_root_hash\x18\x03 \x01(\x0c\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module State
          module Blockrecords
            MigrationWrappedHashes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.blockrecords.MigrationWrappedHashes").msgclass
          end
        end
      end
    end
  end
end
