# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/blockrecords/running_hashes.proto

require 'google/protobuf'


descriptor_data = "\n0services/state/blockrecords/running_hashes.proto\x12\x05proto\"\x85\x01\n\rRunningHashes\x12\x14\n\x0crunning_hash\x18\x01 \x01(\x0c\x12\x1e\n\x16n_minus_1_running_hash\x18\x02 \x01(\x0c\x12\x1e\n\x16n_minus_2_running_hash\x18\x03 \x01(\x0c\x12\x1e\n\x16n_minus_3_running_hash\x18\x04 \x01(\x0c\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  RunningHashes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.RunningHashes").msgclass
end
