# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk/transaction_list.proto

require 'google/protobuf'

require 'hiero/proto/services/transaction_pb'


descriptor_data = "\n\x1asdk/transaction_list.proto\x12\x05proto\x1a\x1aservices/transaction.proto\"?\n\x0fTransactionList\x12,\n\x10transaction_list\x18\x01 \x03(\x0b\x32\x12.proto.TransactionB\"\n\x1e\x63om.hedera.hashgraph.sdk.protoP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TransactionList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TransactionList").msgclass
end
