# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/entity/entity_counts.proto

require 'google/protobuf'


descriptor_data = "\n)services/state/entity/entity_counts.proto\x12!com.hedera.hapi.node.state.entity\"\x97\x03\n\x0c\x45ntityCounts\x12\x14\n\x0cnum_accounts\x18\x01 \x01(\x04\x12\x13\n\x0bnum_aliases\x18\x02 \x01(\x04\x12\x12\n\nnum_tokens\x18\x03 \x01(\x04\x12\x1b\n\x13num_token_relations\x18\x04 \x01(\x04\x12\x10\n\x08num_nfts\x18\x05 \x01(\x04\x12\x14\n\x0cnum_airdrops\x18\x06 \x01(\x04\x12\x19\n\x11num_staking_infos\x18\x07 \x01(\x04\x12\x12\n\nnum_topics\x18\x08 \x01(\x04\x12\x11\n\tnum_files\x18\t \x01(\x04\x12\x11\n\tnum_nodes\x18\n \x01(\x04\x12\x15\n\rnum_schedules\x18\x0b \x01(\x04\x12\"\n\x1anum_contract_storage_slots\x18\x0c \x01(\x04\x12\x1e\n\x16num_contract_bytecodes\x18\r \x01(\x04\x12\x11\n\tnum_hooks\x18\x0e \x01(\x04\x12\"\n\x1anum_evm_hook_storage_slots\x18\x0f \x01(\x04\x12\x1c\n\x14num_registered_nodes\x18\x10 \x01(\x04\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module State
          module Entity
            EntityCounts = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.entity.EntityCounts").msgclass
          end
        end
      end
    end
  end
end
