# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/output/block_header.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/timestamp_pb'


descriptor_data = "\n&block/stream/output/block_header.proto\x12#com.hedera.hapi.block.stream.output\x1a\x1aservices/basic_types.proto\x1a\x18services/timestamp.proto\"\xe1\x01\n\x0b\x42lockHeader\x12\x32\n\x12hapi_proto_version\x18\x01 \x01(\x0b\x32\x16.proto.SemanticVersion\x12\x30\n\x10software_version\x18\x02 \x01(\x0b\x32\x16.proto.SemanticVersion\x12\x0e\n\x06number\x18\x03 \x01(\x04\x12)\n\x0f\x62lock_timestamp\x18\x04 \x01(\x0b\x32\x10.proto.Timestamp\x12\x31\n\x0ehash_algorithm\x18\x05 \x01(\x0e\x32\x19.proto.BlockHashAlgorithmB.\n*com.hedera.hapi.block.stream.output.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          module Output
            BlockHeader = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.BlockHeader").msgclass
          end
        end
      end
    end
  end
end
