# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/output/block_footer.proto

require 'google/protobuf'


descriptor_data = "\n&block/stream/output/block_footer.proto\x12#com.hedera.hapi.block.stream.output\"\x83\x01\n\x0b\x42lockFooter\x12 \n\x18previous_block_root_hash\x18\x01 \x01(\x0c\x12*\n\"root_hash_of_all_block_hashes_tree\x18\x02 \x01(\x0c\x12&\n\x1estart_of_block_state_root_hash\x18\x03 \x01(\x0c\x42.\n*com.hedera.hapi.block.stream.output.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          module Output
            BlockFooter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.BlockFooter").msgclass
          end
        end
      end
    end
  end
end
