# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/output/consensus_service.proto

require 'google/protobuf'


descriptor_data = "\n+block/stream/output/consensus_service.proto\x12#com.hedera.hapi.block.stream.output\"\x13\n\x11\x43reateTopicOutput\"\x13\n\x11UpdateTopicOutput\"\x13\n\x11\x44\x65leteTopicOutput\"\x15\n\x13SubmitMessageOutput*g\n\x12RunningHashVersion\x12!\n\x1dWITH_MESSAGE_DIGEST_AND_PAYER\x10\x00\x12\x17\n\x13WITH_MESSAGE_DIGEST\x10\x01\x12\x15\n\x11WITH_FULL_MESSAGE\x10\x02\x42.\n*com.hedera.hapi.block.stream.output.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          module Output
            CreateTopicOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.CreateTopicOutput").msgclass
            UpdateTopicOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.UpdateTopicOutput").msgclass
            DeleteTopicOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.DeleteTopicOutput").msgclass
            SubmitMessageOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.SubmitMessageOutput").msgclass
            RunningHashVersion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.RunningHashVersion").enummodule
          end
        end
      end
    end
  end
end
