# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/output/crypto_service.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n(block/stream/output/crypto_service.proto\x12#com.hedera.hapi.block.stream.output\x1a\x1aservices/basic_types.proto\"\x18\n\x16\x41pproveAllowanceOutput\"\x17\n\x15\x44\x65leteAllowanceOutput\"C\n\x13\x43reateAccountOutput\x12,\n\x12\x63reated_account_id\x18\x01 \x01(\x0b\x32\x10.proto.AccountID\"\x15\n\x13\x44\x65leteAccountOutput\"\x16\n\x14\x43ryptoTransferOutput\"\x15\n\x13UpdateAccountOutputB.\n*com.hedera.hapi.block.stream.output.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          module Output
            ApproveAllowanceOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.ApproveAllowanceOutput").msgclass
            DeleteAllowanceOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.DeleteAllowanceOutput").msgclass
            CreateAccountOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.CreateAccountOutput").msgclass
            DeleteAccountOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.DeleteAccountOutput").msgclass
            CryptoTransferOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.CryptoTransferOutput").msgclass
            UpdateAccountOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.UpdateAccountOutput").msgclass
          end
        end
      end
    end
  end
end
