# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/output/file_service.proto

require 'google/protobuf'


descriptor_data = "\n&block/stream/output/file_service.proto\x12#com.hedera.hapi.block.stream.output\"\x12\n\x10\x41ppendFileOutput\"\x12\n\x10\x43reateFileOutput\"\x12\n\x10\x44\x65leteFileOutput\"\x12\n\x10UpdateFileOutput\"\x14\n\x12SystemDeleteOutput\"\x16\n\x14SystemUndeleteOutputB.\n*com.hedera.hapi.block.stream.output.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          module Output
            AppendFileOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.AppendFileOutput").msgclass
            CreateFileOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.CreateFileOutput").msgclass
            DeleteFileOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.DeleteFileOutput").msgclass
            UpdateFileOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.UpdateFileOutput").msgclass
            SystemDeleteOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.SystemDeleteOutput").msgclass
            SystemUndeleteOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.SystemUndeleteOutput").msgclass
          end
        end
      end
    end
  end
end
