# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/output/network_service.proto

require 'google/protobuf'


descriptor_data = "\n)block/stream/output/network_service.proto\x12#com.hedera.hapi.block.stream.output\"\x17\n\x15UpdateNodeStakeOutput\"\x0e\n\x0c\x46reezeOutputB.\n*com.hedera.hapi.block.stream.output.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          module Output
            UpdateNodeStakeOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.UpdateNodeStakeOutput").msgclass
            FreezeOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.FreezeOutput").msgclass
          end
        end
      end
    end
  end
end
