# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/output/schedule_service.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n*block/stream/output/schedule_service.proto\x12#com.hedera.hapi.block.stream.output\x1a\x1aservices/basic_types.proto\"v\n\x14\x43reateScheduleOutput\x12&\n\x0bschedule_id\x18\x01 \x01(\x0b\x32\x11.proto.ScheduleID\x12\x36\n\x18scheduled_transaction_id\x18\x02 \x01(\x0b\x32\x14.proto.TransactionID\"\x16\n\x14\x44\x65leteScheduleOutput\"L\n\x12SignScheduleOutput\x12\x36\n\x18scheduled_transaction_id\x18\x01 \x01(\x0b\x32\x14.proto.TransactionIDB.\n*com.hedera.hapi.block.stream.output.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          module Output
            CreateScheduleOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.CreateScheduleOutput").msgclass
            DeleteScheduleOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.DeleteScheduleOutput").msgclass
            SignScheduleOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.SignScheduleOutput").msgclass
          end
        end
      end
    end
  end
end
