# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/output/smart_contract_service.proto

require 'google/protobuf'

require 'hiero/proto/services/contract_types_pb'


descriptor_data = "\n0block/stream/output/smart_contract_service.proto\x12#com.hedera.hapi.block.stream.output\x1a\x1dservices/contract_types.proto\"Q\n\x12\x43\x61llContractOutput\x12;\n\x16\x65vm_transaction_result\x18\x01 \x01(\x0b\x32\x1b.proto.EvmTransactionResult\"S\n\x14\x43reateContractOutput\x12;\n\x16\x65vm_transaction_result\x18\x01 \x01(\x0b\x32\x1b.proto.EvmTransactionResult\"\x16\n\x14UpdateContractOutput\"\x16\n\x14\x44\x65leteContractOutput\"\x1e\n\x1cSystemUnDeleteContractOutput\"\x1c\n\x1aSystemDeleteContractOutput\"\xb0\x01\n\x0e\x45thereumOutput\x12\x42\n\x1b\x65vm_call_transaction_result\x18\x01 \x01(\x0b\x32\x1b.proto.EvmTransactionResultH\x00\x12\x44\n\x1d\x65vm_create_transaction_result\x18\x02 \x01(\x0b\x32\x1b.proto.EvmTransactionResultH\x00\x42\x14\n\x12transaction_resultB.\n*com.hedera.hapi.block.stream.output.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          module Output
            CallContractOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.CallContractOutput").msgclass
            CreateContractOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.CreateContractOutput").msgclass
            UpdateContractOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.UpdateContractOutput").msgclass
            DeleteContractOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.DeleteContractOutput").msgclass
            SystemUnDeleteContractOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.SystemUnDeleteContractOutput").msgclass
            SystemDeleteContractOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.SystemDeleteContractOutput").msgclass
            EthereumOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.EthereumOutput").msgclass
          end
        end
      end
    end
  end
end
