# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/output/token_service.proto

require 'google/protobuf'


descriptor_data = "\n\'block/stream/output/token_service.proto\x12#com.hedera.hapi.block.stream.output\"\x13\n\x11\x43reateTokenOutput\"\x1a\n\x18\x46reezeTokenAccountOutput\"\x1c\n\x1aUnfreezeTokenAccountOutput\"\x15\n\x13GrantTokenKycOutput\"\x16\n\x14RevokeTokenKycOutput\"\x13\n\x11\x44\x65leteTokenOutput\"\x13\n\x11UpdateTokenOutput\"\x11\n\x0fMintTokenOutput\"\x11\n\x0f\x42urnTokenOutput\"\x18\n\x16WipeTokenAccountOutput\"\x16\n\x14\x41ssociateTokenOutput\"\x17\n\x15\x44issociateTokenOutput\"\x1e\n\x1cUpdateTokenFeeScheduleOutput\"\x12\n\x10PauseTokenOutput\"\x14\n\x12UnpauseTokenOutput\"\x17\n\x15UpdateTokenNftsOutput\"\x14\n\x12TokenAirdropOutputB.\n*com.hedera.hapi.block.stream.output.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          module Output
            CreateTokenOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.CreateTokenOutput").msgclass
            FreezeTokenAccountOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.FreezeTokenAccountOutput").msgclass
            UnfreezeTokenAccountOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.UnfreezeTokenAccountOutput").msgclass
            GrantTokenKycOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.GrantTokenKycOutput").msgclass
            RevokeTokenKycOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.RevokeTokenKycOutput").msgclass
            DeleteTokenOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.DeleteTokenOutput").msgclass
            UpdateTokenOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.UpdateTokenOutput").msgclass
            MintTokenOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.MintTokenOutput").msgclass
            BurnTokenOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.BurnTokenOutput").msgclass
            WipeTokenAccountOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.WipeTokenAccountOutput").msgclass
            AssociateTokenOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.AssociateTokenOutput").msgclass
            DissociateTokenOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.DissociateTokenOutput").msgclass
            UpdateTokenFeeScheduleOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.UpdateTokenFeeScheduleOutput").msgclass
            PauseTokenOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.PauseTokenOutput").msgclass
            UnpauseTokenOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.UnpauseTokenOutput").msgclass
            UpdateTokenNftsOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.UpdateTokenNftsOutput").msgclass
            TokenAirdropOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.TokenAirdropOutput").msgclass
          end
        end
      end
    end
  end
end
