# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/output/transaction_output.proto

require 'google/protobuf'

require 'hiero/proto/block/stream/output/schedule_service_pb'
require 'hiero/proto/block/stream/output/util_service_pb'
require 'hiero/proto/block/stream/output/crypto_service_pb'
require 'hiero/proto/block/stream/output/smart_contract_service_pb'


descriptor_data = "\n,block/stream/output/transaction_output.proto\x12#com.hedera.hapi.block.stream.output\x1a*block/stream/output/schedule_service.proto\x1a&block/stream/output/util_service.proto\x1a(block/stream/output/crypto_service.proto\x1a\x30\x62lock/stream/output/smart_contract_service.proto\"\xde\x04\n\x11TransactionOutput\x12H\n\tutil_prng\x18\x01 \x01(\x0b\x32\x33.com.hedera.hapi.block.stream.output.UtilPrngOutputH\x00\x12P\n\rcontract_call\x18\x02 \x01(\x0b\x32\x37.com.hedera.hapi.block.stream.output.CallContractOutputH\x00\x12L\n\rethereum_call\x18\x03 \x01(\x0b\x32\x33.com.hedera.hapi.block.stream.output.EthereumOutputH\x00\x12T\n\x0f\x63ontract_create\x18\x04 \x01(\x0b\x32\x39.com.hedera.hapi.block.stream.output.CreateContractOutputH\x00\x12T\n\x0f\x63reate_schedule\x18\x05 \x01(\x0b\x32\x39.com.hedera.hapi.block.stream.output.CreateScheduleOutputH\x00\x12P\n\rsign_schedule\x18\x06 \x01(\x0b\x32\x37.com.hedera.hapi.block.stream.output.SignScheduleOutputH\x00\x12R\n\x0e\x61\x63\x63ount_create\x18\x07 \x01(\x0b\x32\x38.com.hedera.hapi.block.stream.output.CreateAccountOutputH\x00\x42\r\n\x0btransactionB.\n*com.hedera.hapi.block.stream.output.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          module Output
            TransactionOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.TransactionOutput").msgclass
          end
        end
      end
    end
  end
end
