# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/output/util_service.proto

require 'google/protobuf'


descriptor_data = "\n&block/stream/output/util_service.proto\x12#com.hedera.hapi.block.stream.output\"H\n\x0eUtilPrngOutput\x12\x14\n\nprng_bytes\x18\x01 \x01(\x0cH\x00\x12\x15\n\x0bprng_number\x18\x02 \x01(\rH\x00\x42\t\n\x07\x65ntropyB.\n*com.hedera.hapi.block.stream.output.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          module Output
            UtilPrngOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.output.UtilPrngOutput").msgclass
          end
        end
      end
    end
  end
end
