# frozen_string_literal: true
#
# Generated by bin/generate_protos. Do not edit.
#
# Loads every vendored namespace. Requiring the whole HAPI takes on the order of
# 35 ms warm, and only about 5 ms more than the subset a client SDK strictly
# needs, so there is nothing to be gained by loading it piecemeal. Each namespace
# also has its own entry file for callers who prefer to be explicit:
#
#   require "hiero/proto/services"

require "hiero/proto/version"
require "hiero/proto/block"
require "hiero/proto/fees"
require "hiero/proto/mirror"
require "hiero/proto/platform"
require "hiero/proto/sdk"
require "hiero/proto/services"
require "hiero/proto/streams"
