# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mirror/consensus_service.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/timestamp_pb'
require 'hiero/proto/services/consensus_submit_message_pb'


descriptor_data = "\n\x1emirror/consensus_service.proto\x12\x1b\x63om.hedera.mirror.api.proto\x1a\x1aservices/basic_types.proto\x1a\x18services/timestamp.proto\x1a\'services/consensus_submit_message.proto\"\x9f\x01\n\x13\x43onsensusTopicQuery\x12\x1f\n\x07topicID\x18\x01 \x01(\x0b\x32\x0e.proto.TopicID\x12,\n\x12\x63onsensusStartTime\x18\x02 \x01(\x0b\x32\x10.proto.Timestamp\x12*\n\x10\x63onsensusEndTime\x18\x03 \x01(\x0b\x32\x10.proto.Timestamp\x12\r\n\x05limit\x18\x04 \x01(\x04\"\xd5\x01\n\x16\x43onsensusTopicResponse\x12,\n\x12\x63onsensusTimestamp\x18\x01 \x01(\x0b\x32\x10.proto.Timestamp\x12\x0f\n\x07message\x18\x02 \x01(\x0c\x12\x13\n\x0brunningHash\x18\x03 \x01(\x0c\x12\x16\n\x0esequenceNumber\x18\x04 \x01(\x04\x12\x1a\n\x12runningHashVersion\x18\x05 \x01(\x04\x12\x33\n\tchunkInfo\x18\x06 \x01(\x0b\x32 .proto.ConsensusMessageChunkInfo2\x8d\x01\n\x10\x43onsensusService\x12y\n\x0esubscribeTopic\x12\x30.com.hedera.mirror.api.proto.ConsensusTopicQuery\x1a\x33.com.hedera.mirror.api.proto.ConsensusTopicResponse0\x01\x42\x1f\n\x1b\x63om.hedera.mirror.api.protoP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Mirror
      module Api
        module Proto
          ConsensusTopicQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.mirror.api.proto.ConsensusTopicQuery").msgclass
          ConsensusTopicResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.mirror.api.proto.ConsensusTopicResponse").msgclass
        end
      end
    end
  end
end
