# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mirror/consensus_service.proto for package 'com.hedera.mirror.api.proto'
# Original file comments:
# SPDX-License-Identifier: Apache-2.0
#

require 'grpc'
require 'hiero/proto/mirror/consensus_service_pb'

module Com
  module Hedera
    module Mirror
      module Api
        module Proto
          module ConsensusService
            #
            # The Mirror Service provides the ability to query a stream of Hedera Consensus Service (HCS) messages for an
            # HCS Topic via a specific (possibly open-ended) time range.
            #
            class Service

              include ::GRPC::GenericService

              self.marshal_class_method = :encode
              self.unmarshal_class_method = :decode
              self.service_name = 'com.hedera.mirror.api.proto.ConsensusService'

              rpc :subscribeTopic, ::Com::Hedera::Mirror::Api::Proto::ConsensusTopicQuery, stream(::Com::Hedera::Mirror::Api::Proto::ConsensusTopicResponse)
            end

            Stub = Service.rpc_stub_class
          end
        end
      end
    end
  end
end
