# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mirror/mirror_network_service.proto for package 'com.hedera.mirror.api.proto'

require 'grpc'
require 'hiero/proto/mirror/mirror_network_service_pb'

module Com
  module Hedera
    module Mirror
      module Api
        module Proto
          module NetworkService
            # *
            # Provides cross network APIs like address book queries
            class Service

              include ::GRPC::GenericService

              self.marshal_class_method = :encode
              self.unmarshal_class_method = :decode
              self.service_name = 'com.hedera.mirror.api.proto.NetworkService'

              #
              # Query for an address book and return its nodes. The nodes are returned in ascending order by node ID. The
              # response is not guaranteed to be a byte-for-byte equivalent to the NodeAddress in the Hedera file on
              # the network since it is reconstructed from a normalized database table.
              rpc :getNodes, ::Com::Hedera::Mirror::Api::Proto::AddressBookQuery, stream(::Proto::NodeAddress)
            end

            Stub = Service.rpc_stub_class
          end
        end
      end
    end
  end
end
