# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mirror/mirror_network_service.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/timestamp_pb'


descriptor_data = "\n#mirror/mirror_network_service.proto\x12\x1b\x63om.hedera.mirror.api.proto\x1a\x1aservices/basic_types.proto\x1a\x18services/timestamp.proto\"A\n\x10\x41\x64\x64ressBookQuery\x12\x1e\n\x07\x66ile_id\x18\x01 \x01(\x0b\x32\r.proto.FileID\x12\r\n\x05limit\x18\x02 \x01(\x05\x32\x61\n\x0eNetworkService\x12O\n\x08getNodes\x12-.com.hedera.mirror.api.proto.AddressBookQuery\x1a\x12.proto.NodeAddress0\x01\x42\x1f\n\x1b\x63om.hedera.mirror.api.protoP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Mirror
      module Api
        module Proto
          AddressBookQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.mirror.api.proto.AddressBookQuery").msgclass
        end
      end
    end
  end
end
