# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/token/account_pending_airdrop.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n2services/state/token/account_pending_airdrop.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"\xb4\x01\n\x15\x41\x63\x63ountPendingAirdrop\x12\x39\n\x15pending_airdrop_value\x18\x01 \x01(\x0b\x32\x1a.proto.PendingAirdropValue\x12\x31\n\x10previous_airdrop\x18\x02 \x01(\x0b\x32\x17.proto.PendingAirdropId\x12-\n\x0cnext_airdrop\x18\x03 \x01(\x0b\x32\x17.proto.PendingAirdropIdB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  AccountPendingAirdrop = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.AccountPendingAirdrop").msgclass
end
