# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/token/network_staking_rewards.proto

require 'google/protobuf'

require 'hiero/proto/services/timestamp_pb'


descriptor_data = "\n2services/state/token/network_staking_rewards.proto\x12\x05proto\x1a\x18services/timestamp.proto\"\xcc\x01\n\x15NetworkStakingRewards\x12!\n\x19staking_rewards_activated\x18\x01 \x01(\x08\x12!\n\x19total_staked_reward_start\x18\x02 \x01(\x03\x12\x1a\n\x12total_staked_start\x18\x03 \x01(\x03\x12\x17\n\x0fpending_rewards\x18\x04 \x01(\x03\x12\x38\n\x1elast_node_reward_payments_time\x18\x05 \x01(\x0b\x32\x10.proto.TimestampB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  NetworkStakingRewards = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NetworkStakingRewards").msgclass
end
