# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/token/nft.proto

require 'google/protobuf'

require 'hiero/proto/services/timestamp_pb'
require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1eservices/state/token/nft.proto\x12\x05proto\x1a\x18services/timestamp.proto\x1a\x1aservices/basic_types.proto\"\xfa\x01\n\x03Nft\x12\x1c\n\x06nft_id\x18\x01 \x01(\x0b\x32\x0c.proto.NftID\x12\"\n\x08owner_id\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12$\n\nspender_id\x18\x03 \x01(\x0b\x32\x10.proto.AccountID\x12#\n\tmint_time\x18\x04 \x01(\x0b\x32\x10.proto.Timestamp\x12\x10\n\x08metadata\x18\x05 \x01(\x0c\x12+\n\x15owner_previous_nft_id\x18\x06 \x01(\x0b\x32\x0c.proto.NftID\x12\'\n\x11owner_next_nft_id\x18\x07 \x01(\x0b\x32\x0c.proto.NftIDB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  Nft = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Nft").msgclass
end
