# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/token/node_payments.proto

require 'google/protobuf'

require 'hiero/proto/services/timestamp_pb'
require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n(services/state/token/node_payments.proto\x12 com.hedera.hapi.node.state.token\x1a\x18services/timestamp.proto\x1a\x1aservices/basic_types.proto\"\x8a\x01\n\x0cNodePayments\x12\x39\n\x1flast_node_fee_distribution_time\x18\x01 \x01(\x0b\x32\x10.proto.Timestamp\x12?\n\x08payments\x18\x02 \x03(\x0b\x32-.com.hedera.hapi.node.state.token.NodePayment\"F\n\x0bNodePayment\x12)\n\x0fnode_account_id\x18\x01 \x01(\x0b\x32\x10.proto.AccountID\x12\x0c\n\x04\x66\x65\x65s\x18\x02 \x01(\x04\x42+\n\'com.hedera.hapi.node.state.token.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module State
          module Token
            NodePayments = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.token.NodePayments").msgclass
            NodePayment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.token.NodePayment").msgclass
          end
        end
      end
    end
  end
end
