# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/token/node_rewards.proto

require 'google/protobuf'


descriptor_data = "\n\'services/state/token/node_rewards.proto\x12\x05proto\"~\n\x0bNodeRewards\x12$\n\x1cnum_rounds_in_staking_period\x18\x01 \x01(\x04\x12\x1b\n\x13node_fees_collected\x18\x02 \x01(\x04\x12,\n\x0fnode_activities\x18\x03 \x03(\x0b\x32\x13.proto.NodeActivity\"@\n\x0cNodeActivity\x12\x0f\n\x07node_id\x18\x01 \x01(\x04\x12\x1f\n\x17num_missed_judge_rounds\x18\x02 \x01(\x04\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  NodeRewards = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NodeRewards").msgclass
  NodeActivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NodeActivity").msgclass
end
