# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/token/staking_node_info.proto

require 'google/protobuf'


descriptor_data = "\n,services/state/token/staking_node_info.proto\x12\x05proto\"\xad\x02\n\x0fStakingNodeInfo\x12\x13\n\x0bnode_number\x18\x01 \x01(\x03\x12\x11\n\tmin_stake\x18\x02 \x01(\x03\x12\x11\n\tmax_stake\x18\x03 \x01(\x03\x12\x17\n\x0fstake_to_reward\x18\x04 \x01(\x03\x12\x1b\n\x13stake_to_not_reward\x18\x05 \x01(\x03\x12\x1a\n\x12stake_reward_start\x18\x06 \x01(\x03\x12$\n\x1cunclaimed_stake_reward_start\x18\x07 \x01(\x03\x12\r\n\x05stake\x18\x08 \x01(\x03\x12\x1a\n\x12reward_sum_history\x18\t \x03(\x03\x12\x12\n\x06weight\x18\n \x01(\x05\x42\x02\x18\x01\x12\x17\n\x0fpending_rewards\x18\x0b \x01(\x03\x12\x0f\n\x07\x64\x65leted\x18\x0c \x01(\x08\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  StakingNodeInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.StakingNodeInfo").msgclass
end
