# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/token/token_relation.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n)services/state/token/token_relation.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"\xf8\x01\n\rTokenRelation\x12 \n\x08token_id\x18\x01 \x01(\x0b\x32\x0e.proto.TokenID\x12$\n\naccount_id\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x03\x12\x0e\n\x06\x66rozen\x18\x04 \x01(\x08\x12\x13\n\x0bkyc_granted\x18\x05 \x01(\x08\x12\x1d\n\x15\x61utomatic_association\x18\x06 \x01(\x08\x12&\n\x0eprevious_token\x18\x07 \x01(\x0b\x32\x0e.proto.TokenID\x12\"\n\nnext_token\x18\x08 \x01(\x0b\x32\x0e.proto.TokenIDB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TokenRelation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenRelation").msgclass
end
