# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/auxiliary/history/history_proof_vote.proto

require 'google/protobuf'

require 'hiero/proto/services/state/history/history_types_pb'


descriptor_data = "\n3services/auxiliary/history/history_proof_vote.proto\x12*com.hedera.hapi.services.auxiliary.history\x1a*services/state/history/history_types.proto\"~\n\x1fHistoryProofVoteTransactionBody\x12\x17\n\x0f\x63onstruction_id\x18\x01 \x01(\x04\x12\x42\n\x04vote\x18\x02 \x01(\x0b\x32\x34.com.hedera.hapi.node.state.history.HistoryProofVoteB5\n1com.hedera.hapi.services.auxiliary.history.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Services
        module Auxiliary
          module History
            HistoryProofVoteTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.services.auxiliary.history.HistoryProofVoteTransactionBody").msgclass
          end
        end
      end
    end
  end
end
