# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/auxiliary/history/history_proof_key_publication.proto

require 'google/protobuf'

require 'hiero/proto/services/state/history/history_types_pb'


descriptor_data = "\n>services/auxiliary/history/history_proof_key_publication.proto\x12*com.hedera.hapi.services.auxiliary.history\x1a*services/state/history/history_types.proto\"\xb9\x01\n)HistoryProofKeyPublicationTransactionBody\x12\x13\n\tproof_key\x18\x01 \x01(\x0cH\x00\x12\x17\n\rwraps_message\x18\x02 \x01(\x0cH\x00\x12\x17\n\x0f\x63onstruction_id\x18\x03 \x01(\x04\x12=\n\x05phase\x18\x04 \x01(\x0e\x32..com.hedera.hapi.node.state.history.WrapsPhaseB\x06\n\x04\x64\x61taB5\n1com.hedera.hapi.services.auxiliary.history.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Services
        module Auxiliary
          module History
            HistoryProofKeyPublicationTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.services.auxiliary.history.HistoryProofKeyPublicationTransactionBody").msgclass
          end
        end
      end
    end
  end
end
