# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/address_book_service.proto

require 'google/protobuf'

require 'hiero/proto/services/transaction_response_pb'
require 'hiero/proto/services/transaction_pb'


descriptor_data = "\n#services/address_book_service.proto\x12\x05proto\x1a#services/transaction_response.proto\x1a\x1aservices/transaction.proto2\xa6\x03\n\x12\x41\x64\x64ressBookService\x12<\n\ncreateNode\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12<\n\ndeleteNode\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12<\n\nupdateNode\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12\x46\n\x14\x63reateRegisteredNode\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12\x46\n\x14\x64\x65leteRegisteredNode\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12\x46\n\x14updateRegisteredNode\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponseB(\n&com.hederahashgraph.service.proto.javab\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
end
