# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/consensus_get_topic_info.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'
require 'hiero/proto/services/consensus_topic_info_pb'


descriptor_data = "\n\'services/consensus_get_topic_info.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\x1a#services/consensus_topic_info.proto\"a\n\x1a\x43onsensusGetTopicInfoQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12\x1f\n\x07topicID\x18\x02 \x01(\x0b\x32\x0e.proto.TopicID\"\x95\x01\n\x1d\x43onsensusGetTopicInfoResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12\x1f\n\x07topicID\x18\x02 \x01(\x0b\x32\x0e.proto.TopicID\x12,\n\ttopicInfo\x18\x05 \x01(\x0b\x32\x19.proto.ConsensusTopicInfoB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ConsensusGetTopicInfoQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ConsensusGetTopicInfoQuery").msgclass
  ConsensusGetTopicInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ConsensusGetTopicInfoResponse").msgclass
end
