# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/consensus_submit_message.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\'services/consensus_submit_message.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"n\n\x19\x43onsensusMessageChunkInfo\x12\x32\n\x14initialTransactionID\x18\x01 \x01(\x0b\x32\x14.proto.TransactionID\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x0e\n\x06number\x18\x03 \x01(\x05\"\x8e\x01\n%ConsensusSubmitMessageTransactionBody\x12\x1f\n\x07topicID\x18\x01 \x01(\x0b\x32\x0e.proto.TopicID\x12\x0f\n\x07message\x18\x02 \x01(\x0c\x12\x33\n\tchunkInfo\x18\x03 \x01(\x0b\x32 .proto.ConsensusMessageChunkInfoB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ConsensusMessageChunkInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ConsensusMessageChunkInfo").msgclass
  ConsensusSubmitMessageTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ConsensusSubmitMessageTransactionBody").msgclass
end
