# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/consensus_create_topic.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/custom_fees_pb'
require 'hiero/proto/services/duration_pb'


descriptor_data = "\n%services/consensus_create_topic.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1aservices/custom_fees.proto\x1a\x17services/duration.proto\"\xc1\x02\n#ConsensusCreateTopicTransactionBody\x12\x0c\n\x04memo\x18\x01 \x01(\t\x12\x1c\n\x08\x61\x64minKey\x18\x02 \x01(\x0b\x32\n.proto.Key\x12\x1d\n\tsubmitKey\x18\x03 \x01(\x0b\x32\n.proto.Key\x12(\n\x0f\x61utoRenewPeriod\x18\x06 \x01(\x0b\x32\x0f.proto.Duration\x12*\n\x10\x61utoRenewAccount\x18\x07 \x01(\x0b\x32\x10.proto.AccountID\x12$\n\x10\x66\x65\x65_schedule_key\x18\x08 \x01(\x0b\x32\n.proto.Key\x12\'\n\x13\x66\x65\x65_exempt_key_list\x18\t \x03(\x0b\x32\n.proto.Key\x12*\n\x0b\x63ustom_fees\x18\n \x03(\x0b\x32\x15.proto.FixedCustomFeeB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ConsensusCreateTopicTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ConsensusCreateTopicTransactionBody").msgclass
end
