# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/consensus_delete_topic.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n%services/consensus_delete_topic.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"F\n#ConsensusDeleteTopicTransactionBody\x12\x1f\n\x07topicID\x18\x01 \x01(\x0b\x32\x0e.proto.TopicIDB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ConsensusDeleteTopicTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ConsensusDeleteTopicTransactionBody").msgclass
end
