# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/contract_get_bytecode.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'


descriptor_data = "\n$services/contract_get_bytecode.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\"e\n\x18\x43ontractGetBytecodeQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12%\n\ncontractID\x18\x02 \x01(\x0b\x32\x11.proto.ContractID\"V\n\x1b\x43ontractGetBytecodeResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12\x10\n\x08\x62ytecode\x18\x06 \x01(\x0c\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ContractGetBytecodeQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractGetBytecodeQuery").msgclass
  ContractGetBytecodeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractGetBytecodeResponse").msgclass
end
