# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/contract_call.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1cservices/contract_call.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"}\n\x1b\x43ontractCallTransactionBody\x12%\n\ncontractID\x18\x01 \x01(\x0b\x32\x11.proto.ContractID\x12\x0b\n\x03gas\x18\x02 \x01(\x03\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\x12\x1a\n\x12\x66unctionParameters\x18\x04 \x01(\x0c\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ContractCallTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractCallTransactionBody").msgclass
end
