# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/contract_get_info.proto

require 'google/protobuf'

require 'hiero/proto/services/timestamp_pb'
require 'hiero/proto/services/duration_pb'
require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'


descriptor_data = "\n services/contract_get_info.proto\x12\x05proto\x1a\x18services/timestamp.proto\x1a\x17services/duration.proto\x1a\x1aservices/basic_types.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\"a\n\x14\x43ontractGetInfoQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12%\n\ncontractID\x18\x02 \x01(\x0b\x32\x11.proto.ContractID\"\x80\x05\n\x17\x43ontractGetInfoResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12\x41\n\x0c\x63ontractInfo\x18\x02 \x01(\x0b\x32+.proto.ContractGetInfoResponse.ContractInfo\x1a\xfa\x03\n\x0c\x43ontractInfo\x12%\n\ncontractID\x18\x01 \x01(\x0b\x32\x11.proto.ContractID\x12#\n\taccountID\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12\x19\n\x11\x63ontractAccountID\x18\x03 \x01(\t\x12\x1c\n\x08\x61\x64minKey\x18\x04 \x01(\x0b\x32\n.proto.Key\x12(\n\x0e\x65xpirationTime\x18\x05 \x01(\x0b\x32\x10.proto.Timestamp\x12(\n\x0f\x61utoRenewPeriod\x18\x06 \x01(\x0b\x32\x0f.proto.Duration\x12\x0f\n\x07storage\x18\x07 \x01(\x03\x12\x0c\n\x04memo\x18\x08 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\t \x01(\x04\x12\x0f\n\x07\x64\x65leted\x18\n \x01(\x08\x12\x38\n\x12tokenRelationships\x18\x0b \x03(\x0b\x32\x18.proto.TokenRelationshipB\x02\x18\x01\x12\x11\n\tledger_id\x18\x0c \x01(\x0c\x12/\n\x15\x61uto_renew_account_id\x18\r \x01(\x0b\x32\x10.proto.AccountID\x12(\n max_automatic_token_associations\x18\x0e \x01(\x05\x12(\n\x0cstaking_info\x18\x0f \x01(\x0b\x32\x12.proto.StakingInfoB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ContractGetInfoQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractGetInfoQuery").msgclass
  ContractGetInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractGetInfoResponse").msgclass
  ContractGetInfoResponse::ContractInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractGetInfoResponse.ContractInfo").msgclass
end
