# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/contract_update.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/duration_pb'
require 'hiero/proto/services/hook_types_pb'
require 'hiero/proto/services/timestamp_pb'
require 'google/protobuf/wrappers_pb'


descriptor_data = "\n\x1eservices/contract_update.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x17services/duration.proto\x1a\x19services/hook_types.proto\x1a\x18services/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xcd\x05\n\x1d\x43ontractUpdateTransactionBody\x12%\n\ncontractID\x18\x01 \x01(\x0b\x32\x11.proto.ContractID\x12(\n\x0e\x65xpirationTime\x18\x02 \x01(\x0b\x32\x10.proto.Timestamp\x12\x1c\n\x08\x61\x64minKey\x18\x03 \x01(\x0b\x32\n.proto.Key\x12,\n\x0eproxyAccountID\x18\x06 \x01(\x0b\x32\x10.proto.AccountIDB\x02\x18\x01\x12(\n\x0f\x61utoRenewPeriod\x18\x07 \x01(\x0b\x32\x0f.proto.Duration\x12!\n\x06\x66ileID\x18\x08 \x01(\x0b\x32\r.proto.FileIDB\x02\x18\x01\x12\x12\n\x04memo\x18\t \x01(\tB\x02\x18\x01H\x00\x12\x33\n\x0bmemoWrapper\x18\n \x01(\x0b\x32\x1c.google.protobuf.StringValueH\x00\x12\x45\n max_automatic_token_associations\x18\x0b \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12/\n\x15\x61uto_renew_account_id\x18\x0c \x01(\x0b\x32\x10.proto.AccountID\x12-\n\x11staked_account_id\x18\r \x01(\x0b\x32\x10.proto.AccountIDH\x01\x12\x18\n\x0estaked_node_id\x18\x0e \x01(\x03H\x01\x12\x32\n\x0e\x64\x65\x63line_reward\x18\x0f \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x1a\n\x12hook_ids_to_delete\x18\x10 \x03(\x03\x12N\n\x15hook_creation_details\x18\x11 \x03(\x0b\x32/.com.hedera.hapi.node.hooks.HookCreationDetailsB\x0b\n\tmemoFieldB\x0b\n\tstaked_idB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ContractUpdateTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractUpdateTransactionBody").msgclass
end
