# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/contract_delete.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1eservices/contract_delete.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"\xce\x01\n\x1d\x43ontractDeleteTransactionBody\x12%\n\ncontractID\x18\x01 \x01(\x0b\x32\x11.proto.ContractID\x12-\n\x11transferAccountID\x18\x02 \x01(\x0b\x32\x10.proto.AccountIDH\x00\x12/\n\x12transferContractID\x18\x03 \x01(\x0b\x32\x11.proto.ContractIDH\x00\x12\x19\n\x11permanent_removal\x18\x04 \x01(\x08\x42\x0b\n\tobtainersB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ContractDeleteTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractDeleteTransactionBody").msgclass
end
