# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/contract_call_local.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/contract_types_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'


descriptor_data = "\n\"services/contract_call_local.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1dservices/contract_types.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\"\xcc\x01\n\x16\x43ontractCallLocalQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12%\n\ncontractID\x18\x02 \x01(\x0b\x32\x11.proto.ContractID\x12\x0b\n\x03gas\x18\x03 \x01(\x03\x12\x1a\n\x12\x66unctionParameters\x18\x04 \x01(\x0c\x12\x19\n\rmaxResultSize\x18\x05 \x01(\x03\x42\x02\x18\x01\x12#\n\tsender_id\x18\x06 \x01(\x0b\x32\x10.proto.AccountID\"y\n\x19\x43ontractCallLocalResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12\x35\n\x0e\x66unctionResult\x18\x02 \x01(\x0b\x32\x1d.proto.ContractFunctionResultB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ContractCallLocalQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractCallLocalQuery").msgclass
  ContractCallLocalResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractCallLocalResponse").msgclass
end
