# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/contract_get_records.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/transaction_record_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'


descriptor_data = "\n#services/contract_get_records.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a!services/transaction_record.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\"h\n\x17\x43ontractGetRecordsQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12%\n\ncontractID\x18\x02 \x01(\x0b\x32\x11.proto.ContractID:\x02\x18\x01\"\x99\x01\n\x1a\x43ontractGetRecordsResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12%\n\ncontractID\x18\x02 \x01(\x0b\x32\x11.proto.ContractID\x12)\n\x07records\x18\x03 \x03(\x0b\x32\x18.proto.TransactionRecord:\x02\x18\x01\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ContractGetRecordsQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractGetRecordsQuery").msgclass
  ContractGetRecordsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ContractGetRecordsResponse").msgclass
end
