# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/crypto_create.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/duration_pb'
require 'hiero/proto/services/hook_types_pb'


descriptor_data = "\n\x1cservices/crypto_create.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x17services/duration.proto\x1a\x19services/hook_types.proto\"\xa1\x05\n\x1b\x43ryptoCreateTransactionBody\x12\x17\n\x03key\x18\x01 \x01(\x0b\x32\n.proto.Key\x12\x16\n\x0einitialBalance\x18\x02 \x01(\x04\x12,\n\x0eproxyAccountID\x18\x03 \x01(\x0b\x32\x10.proto.AccountIDB\x02\x18\x01\x12\x1f\n\x13sendRecordThreshold\x18\x06 \x01(\x04\x42\x02\x18\x01\x12\"\n\x16receiveRecordThreshold\x18\x07 \x01(\x04\x42\x02\x18\x01\x12\x1b\n\x13receiverSigRequired\x18\x08 \x01(\x08\x12(\n\x0f\x61utoRenewPeriod\x18\t \x01(\x0b\x32\x0f.proto.Duration\x12\x1f\n\x07shardID\x18\n \x01(\x0b\x32\x0e.proto.ShardID\x12\x1f\n\x07realmID\x18\x0b \x01(\x0b\x32\x0e.proto.RealmID\x12(\n\x10newRealmAdminKey\x18\x0c \x01(\x0b\x32\n.proto.KeyB\x02\x18\x01\x12\x0c\n\x04memo\x18\r \x01(\t\x12(\n max_automatic_token_associations\x18\x0e \x01(\x05\x12-\n\x11staked_account_id\x18\x0f \x01(\x0b\x32\x10.proto.AccountIDH\x00\x12\x18\n\x0estaked_node_id\x18\x10 \x01(\x03H\x00\x12\x16\n\x0e\x64\x65\x63line_reward\x18\x11 \x01(\x08\x12\r\n\x05\x61lias\x18\x12 \x01(\x0c\x12N\n\x15hook_creation_details\x18\x13 \x03(\x0b\x32/.com.hedera.hapi.node.hooks.HookCreationDetails\x12\x1a\n\x12\x64\x65legation_address\x18\x14 \x01(\x0c\x42\x0b\n\tstaked_idJ\x04\x08\x04\x10\x05J\x04\x08\x05\x10\x06\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  CryptoCreateTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CryptoCreateTransactionBody").msgclass
end
