# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/crypto_get_account_records.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/transaction_record_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'


descriptor_data = "\n)services/crypto_get_account_records.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a!services/transaction_record.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\"g\n\x1c\x43ryptoGetAccountRecordsQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12#\n\taccountID\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\"\x98\x01\n\x1f\x43ryptoGetAccountRecordsResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12#\n\taccountID\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12)\n\x07records\x18\x03 \x03(\x0b\x32\x18.proto.TransactionRecordB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  CryptoGetAccountRecordsQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CryptoGetAccountRecordsQuery").msgclass
  CryptoGetAccountRecordsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CryptoGetAccountRecordsResponse").msgclass
end
