# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/crypto_delete_live_hash.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n&services/crypto_delete_live_hash.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"l\n#CryptoDeleteLiveHashTransactionBody\x12+\n\x11\x61\x63\x63ountOfLiveHash\x18\x01 \x01(\x0b\x32\x10.proto.AccountID\x12\x18\n\x10liveHashToDelete\x18\x02 \x01(\x0c\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  CryptoDeleteLiveHashTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CryptoDeleteLiveHashTransactionBody").msgclass
end
