# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/crypto_add_live_hash.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/duration_pb'


descriptor_data = "\n#services/crypto_add_live_hash.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x17services/duration.proto\"~\n\x08LiveHash\x12#\n\taccountId\x18\x01 \x01(\x0b\x32\x10.proto.AccountID\x12\x0c\n\x04hash\x18\x02 \x01(\x0c\x12\x1c\n\x04keys\x18\x03 \x01(\x0b\x32\x0e.proto.KeyList\x12!\n\x08\x64uration\x18\x05 \x01(\x0b\x32\x0f.proto.Duration\"E\n CryptoAddLiveHashTransactionBody\x12!\n\x08liveHash\x18\x03 \x01(\x0b\x32\x0f.proto.LiveHashB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  LiveHash = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.LiveHash").msgclass
  CryptoAddLiveHashTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CryptoAddLiveHashTransactionBody").msgclass
end
