# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: services/crypto_service.proto for package 'proto'
# Original file comments:
# *
# # Crypto Service
# A service defining transactions and queries related to accounts.
#
# This includes transactions for HBAR transfers and balance queries as well as
# transactions to manage "allowances" which permit a third party to spend a
# portion of the HBAR balance in an account.<br/>
# Basic account, record, and receipt queries are also defined in this service.
#
# Transactions and queries relating to tokens _other than HBAR_ are defined
# in the Token Service.
#
# ### Keywords
# The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
# "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
# document are to be interpreted as described in
# [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
# [RFC8174](https://www.ietf.org/rfc/rfc8174).

require 'grpc'
require 'hiero/proto/services/crypto_service_pb'

module Proto
  module CryptoService
    # *
    # Transactions and queries for the Hedera Crypto Service.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'proto.CryptoService'

      # *
      # Create a new account by submitting the transaction
      rpc :createAccount, ::Proto::Transaction, ::Proto::TransactionResponse
      # *
      # Update an account by submitting the transaction
      rpc :updateAccount, ::Proto::Transaction, ::Proto::TransactionResponse
      # *
      # Initiate a transfer by submitting the transaction
      rpc :cryptoTransfer, ::Proto::Transaction, ::Proto::TransactionResponse
      # *
      # Delete an account by submitting the transaction
      rpc :cryptoDelete, ::Proto::Transaction, ::Proto::TransactionResponse
      # *
      # Add one or more approved allowances for spenders to transfer the paying
      # account's hbar or tokens.
      rpc :approveAllowances, ::Proto::Transaction, ::Proto::TransactionResponse
      # *
      # Delete one or more of the specific approved NFT serial numbers on an
      # owner account.
      rpc :deleteAllowances, ::Proto::Transaction, ::Proto::TransactionResponse
      # *
      # Add a livehash
      # <blockquote>Important<blockquote>
      # This transaction is obsolete, not supported, and SHALL fail with a
      # pre-check result of `NOT_SUPPORTED`.</blockquote></blockquote>
      rpc :addLiveHash, ::Proto::Transaction, ::Proto::TransactionResponse
      # *
      # Delete a livehash
      # <blockquote>Important<blockquote>
      # This transaction is obsolete, not supported, and SHALL fail with a
      # pre-check result of `NOT_SUPPORTED`.</blockquote></blockquote>
      rpc :deleteLiveHash, ::Proto::Transaction, ::Proto::TransactionResponse
      # *
      # Retrieve a livehash for an account
      # <blockquote>Important<blockquote>
      # This query is obsolete, not supported, and SHALL fail with a pre-check
      # result of `NOT_SUPPORTED`.</blockquote></blockquote>
      rpc :getLiveHash, ::Proto::Query, ::Proto::Response
      # *
      # Return all transactions in the last 180s of consensus time for which
      # the given account was the effective payer **and** network property
      # `ledger.keepRecordsInState` was `true`.
      rpc :getAccountRecords, ::Proto::Query, ::Proto::Response
      # *
      # Retrieve the balance of an account
      rpc :cryptoGetBalance, ::Proto::Query, ::Proto::Response
      # *
      # Retrieve the metadata of an account
      rpc :getAccountInfo, ::Proto::Query, ::Proto::Response
      # *
      # Retrieve the latest receipt for a transaction that is either awaiting
      # consensus, or reached consensus in the last 180 seconds
      rpc :getTransactionReceipts, ::Proto::Query, ::Proto::Response
      # *
      # Retrieve the record of a transaction that is either awaiting consensus,
      # or reached consensus in the last 180 seconds
      rpc :getTxRecordByTxID, ::Proto::Query, ::Proto::Response
    end

    Stub = Service.rpc_stub_class
  end
  # The following queries are permanently removed.
  # getStakersByAccountID, getFastTransactionRecord
end
