# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/crypto_update.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/duration_pb'
require 'hiero/proto/services/hook_types_pb'
require 'hiero/proto/services/timestamp_pb'
require 'google/protobuf/wrappers_pb'


descriptor_data = "\n\x1cservices/crypto_update.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x17services/duration.proto\x1a\x19services/hook_types.proto\x1a\x18services/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x9d\x08\n\x1b\x43ryptoUpdateTransactionBody\x12+\n\x11\x61\x63\x63ountIDToUpdate\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12\x17\n\x03key\x18\x03 \x01(\x0b\x32\n.proto.Key\x12,\n\x0eproxyAccountID\x18\x04 \x01(\x0b\x32\x10.proto.AccountIDB\x02\x18\x01\x12\x19\n\rproxyFraction\x18\x05 \x01(\x05\x42\x02\x18\x01\x12!\n\x13sendRecordThreshold\x18\x06 \x01(\x04\x42\x02\x18\x01H\x00\x12\x46\n\x1asendRecordThresholdWrapper\x18\x0b \x01(\x0b\x32\x1c.google.protobuf.UInt64ValueB\x02\x18\x01H\x00\x12$\n\x16receiveRecordThreshold\x18\x07 \x01(\x04\x42\x02\x18\x01H\x01\x12I\n\x1dreceiveRecordThresholdWrapper\x18\x0c \x01(\x0b\x32\x1c.google.protobuf.UInt64ValueB\x02\x18\x01H\x01\x12(\n\x0f\x61utoRenewPeriod\x18\x08 \x01(\x0b\x32\x0f.proto.Duration\x12(\n\x0e\x65xpirationTime\x18\t \x01(\x0b\x32\x10.proto.Timestamp\x12!\n\x13receiverSigRequired\x18\n \x01(\x08\x42\x02\x18\x01H\x02\x12@\n\x1areceiverSigRequiredWrapper\x18\r \x01(\x0b\x32\x1a.google.protobuf.BoolValueH\x02\x12*\n\x04memo\x18\x0e \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x45\n max_automatic_token_associations\x18\x0f \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12-\n\x11staked_account_id\x18\x10 \x01(\x0b\x32\x10.proto.AccountIDH\x03\x12\x18\n\x0estaked_node_id\x18\x11 \x01(\x03H\x03\x12\x32\n\x0e\x64\x65\x63line_reward\x18\x12 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x1a\n\x12hook_ids_to_delete\x18\x13 \x03(\x03\x12N\n\x15hook_creation_details\x18\x14 \x03(\x0b\x32/.com.hedera.hapi.node.hooks.HookCreationDetails\x12\x1a\n\x12\x64\x65legation_address\x18\x15 \x01(\x0c\x42\x1a\n\x18sendRecordThresholdFieldB\x1d\n\x1breceiveRecordThresholdFieldB\x1a\n\x18receiverSigRequiredFieldB\x0b\n\tstaked_idB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  CryptoUpdateTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CryptoUpdateTransactionBody").msgclass
end
