# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/crypto_get_account_balance.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'


descriptor_data = "\n)services/crypto_get_account_balance.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\"\xa3\x01\n\x1c\x43ryptoGetAccountBalanceQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12%\n\taccountID\x18\x02 \x01(\x0b\x32\x10.proto.AccountIDH\x00\x12\'\n\ncontractID\x18\x03 \x01(\x0b\x32\x11.proto.ContractIDH\x00\x42\x0f\n\rbalanceSource\"\xae\x01\n\x1f\x43ryptoGetAccountBalanceResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12#\n\taccountID\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x04\x12.\n\rtokenBalances\x18\x04 \x03(\x0b\x32\x13.proto.TokenBalanceB\x02\x18\x01\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  CryptoGetAccountBalanceQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CryptoGetAccountBalanceQuery").msgclass
  CryptoGetAccountBalanceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CryptoGetAccountBalanceResponse").msgclass
end
