# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/crypto_transfer.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1eservices/crypto_transfer.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"y\n\x1d\x43ryptoTransferTransactionBody\x12&\n\ttransfers\x18\x01 \x01(\x0b\x32\x13.proto.TransferList\x12\x30\n\x0etokenTransfers\x18\x02 \x03(\x0b\x32\x18.proto.TokenTransferListB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  CryptoTransferTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CryptoTransferTransactionBody").msgclass
end
