# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/crypto_get_live_hash.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'
require 'hiero/proto/services/crypto_add_live_hash_pb'


descriptor_data = "\n#services/crypto_get_live_hash.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\x1a#services/crypto_add_live_hash.proto\"o\n\x16\x43ryptoGetLiveHashQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12#\n\taccountID\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12\x0c\n\x04hash\x18\x03 \x01(\x0c\"e\n\x19\x43ryptoGetLiveHashResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12!\n\x08liveHash\x18\x02 \x01(\x0b\x32\x0f.proto.LiveHashB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  CryptoGetLiveHashQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CryptoGetLiveHashQuery").msgclass
  CryptoGetLiveHashResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CryptoGetLiveHashResponse").msgclass
end
