# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/crypto_approve_allowance.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'google/protobuf/wrappers_pb'


descriptor_data = "\n\'services/crypto_approve_allowance.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb5\x01\n%CryptoApproveAllowanceTransactionBody\x12\x30\n\x10\x63ryptoAllowances\x18\x01 \x03(\x0b\x32\x16.proto.CryptoAllowance\x12*\n\rnftAllowances\x18\x02 \x03(\x0b\x32\x13.proto.NftAllowance\x12.\n\x0ftokenAllowances\x18\x03 \x03(\x0b\x32\x15.proto.TokenAllowance\"e\n\x0f\x43ryptoAllowance\x12\x1f\n\x05owner\x18\x01 \x01(\x0b\x32\x10.proto.AccountID\x12!\n\x07spender\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\"\xef\x01\n\x0cNftAllowance\x12\x1f\n\x07tokenId\x18\x01 \x01(\x0b\x32\x0e.proto.TokenID\x12\x1f\n\x05owner\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12!\n\x07spender\x18\x03 \x01(\x0b\x32\x10.proto.AccountID\x12\x16\n\x0eserial_numbers\x18\x04 \x03(\x03\x12\x34\n\x10\x61pproved_for_all\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12,\n\x12\x64\x65legating_spender\x18\x06 \x01(\x0b\x32\x10.proto.AccountID\"\x85\x01\n\x0eTokenAllowance\x12\x1f\n\x07tokenId\x18\x01 \x01(\x0b\x32\x0e.proto.TokenID\x12\x1f\n\x05owner\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12!\n\x07spender\x18\x03 \x01(\x0b\x32\x10.proto.AccountID\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x03\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  CryptoApproveAllowanceTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CryptoApproveAllowanceTransactionBody").msgclass
  CryptoAllowance = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CryptoAllowance").msgclass
  NftAllowance = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NftAllowance").msgclass
  TokenAllowance = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenAllowance").msgclass
end
