# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/crypto_service.proto

require 'google/protobuf'

require 'hiero/proto/services/query_pb'
require 'hiero/proto/services/response_pb'
require 'hiero/proto/services/transaction_response_pb'
require 'hiero/proto/services/transaction_pb'


descriptor_data = "\n\x1dservices/crypto_service.proto\x12\x05proto\x1a\x14services/query.proto\x1a\x17services/response.proto\x1a#services/transaction_response.proto\x1a\x1aservices/transaction.proto2\xdf\x06\n\rCryptoService\x12?\n\rcreateAccount\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12?\n\rupdateAccount\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12@\n\x0e\x63ryptoTransfer\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12>\n\x0c\x63ryptoDelete\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12\x43\n\x11\x61pproveAllowances\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12\x42\n\x10\x64\x65leteAllowances\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12\x42\n\x0b\x61\x64\x64LiveHash\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\"\x03\x88\x02\x01\x12\x45\n\x0e\x64\x65leteLiveHash\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\"\x03\x88\x02\x01\x12\x31\n\x0bgetLiveHash\x12\x0c.proto.Query\x1a\x0f.proto.Response\"\x03\x88\x02\x01\x12\x32\n\x11getAccountRecords\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12\x31\n\x10\x63ryptoGetBalance\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12/\n\x0egetAccountInfo\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12\x37\n\x16getTransactionReceipts\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12\x32\n\x11getTxRecordByTxID\x12\x0c.proto.Query\x1a\x0f.proto.ResponseB(\n&com.hederahashgraph.service.proto.javab\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
end
