# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/crypto_delete_allowance.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n&services/crypto_delete_allowance.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"X\n$CryptoDeleteAllowanceTransactionBody\x12\x30\n\rnftAllowances\x18\x02 \x03(\x0b\x32\x19.proto.NftRemoveAllowance\"o\n\x12NftRemoveAllowance\x12 \n\x08token_id\x18\x01 \x01(\x0b\x32\x0e.proto.TokenID\x12\x1f\n\x05owner\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12\x16\n\x0eserial_numbers\x18\x03 \x03(\x03\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  CryptoDeleteAllowanceTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CryptoDeleteAllowanceTransactionBody").msgclass
  NftRemoveAllowance = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NftRemoveAllowance").msgclass
end
