# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/crypto_delete.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1cservices/crypto_delete.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"u\n\x1b\x43ryptoDeleteTransactionBody\x12+\n\x11transferAccountID\x18\x01 \x01(\x0b\x32\x10.proto.AccountID\x12)\n\x0f\x64\x65leteAccountID\x18\x02 \x01(\x0b\x32\x10.proto.AccountIDB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  CryptoDeleteTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CryptoDeleteTransactionBody").msgclass
end
