# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/custom_fees.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1aservices/custom_fees.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"\x85\x01\n\rFractionalFee\x12*\n\x11\x66ractional_amount\x18\x01 \x01(\x0b\x32\x0f.proto.Fraction\x12\x16\n\x0eminimum_amount\x18\x02 \x01(\x03\x12\x16\n\x0emaximum_amount\x18\x03 \x01(\x03\x12\x18\n\x10net_of_transfers\x18\x04 \x01(\x08\"I\n\x08\x46ixedFee\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x03\x12-\n\x15\x64\x65nominating_token_id\x18\x02 \x01(\x0b\x32\x0e.proto.TokenID\"e\n\nRoyaltyFee\x12\x30\n\x17\x65xchange_value_fraction\x18\x01 \x01(\x0b\x32\x0f.proto.Fraction\x12%\n\x0c\x66\x61llback_fee\x18\x02 \x01(\x0b\x32\x0f.proto.FixedFee\"\xe9\x01\n\tCustomFee\x12$\n\tfixed_fee\x18\x01 \x01(\x0b\x32\x0f.proto.FixedFeeH\x00\x12.\n\x0e\x66ractional_fee\x18\x02 \x01(\x0b\x32\x14.proto.FractionalFeeH\x00\x12(\n\x0broyalty_fee\x18\x04 \x01(\x0b\x32\x11.proto.RoyaltyFeeH\x00\x12\x32\n\x18\x66\x65\x65_collector_account_id\x18\x03 \x01(\x0b\x32\x10.proto.AccountID\x12!\n\x19\x61ll_collectors_are_exempt\x18\x05 \x01(\x08\x42\x05\n\x03\x66\x65\x65\"\xaf\x01\n\x11\x41ssessedCustomFee\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x03\x12 \n\x08token_id\x18\x02 \x01(\x0b\x32\x0e.proto.TokenID\x12\x32\n\x18\x66\x65\x65_collector_account_id\x18\x03 \x01(\x0b\x32\x10.proto.AccountID\x12\x34\n\x1a\x65\x66\x66\x65\x63tive_payer_account_id\x18\x04 \x03(\x0b\x32\x10.proto.AccountID\"h\n\x0e\x46ixedCustomFee\x12\"\n\tfixed_fee\x18\x01 \x01(\x0b\x32\x0f.proto.FixedFee\x12\x32\n\x18\x66\x65\x65_collector_account_id\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\"9\n\x12\x46ixedCustomFeeList\x12#\n\x04\x66\x65\x65s\x18\x01 \x03(\x0b\x32\x15.proto.FixedCustomFee\",\n\x10\x46\x65\x65\x45xemptKeyList\x12\x18\n\x04keys\x18\x01 \x03(\x0b\x32\n.proto.Key\"U\n\x0e\x43ustomFeeLimit\x12$\n\naccount_id\x18\x01 \x01(\x0b\x32\x10.proto.AccountID\x12\x1d\n\x04\x66\x65\x65s\x18\x02 \x03(\x0b\x32\x0f.proto.FixedFeeB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  FractionalFee = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.FractionalFee").msgclass
  FixedFee = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.FixedFee").msgclass
  RoyaltyFee = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.RoyaltyFee").msgclass
  CustomFee = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CustomFee").msgclass
  AssessedCustomFee = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.AssessedCustomFee").msgclass
  FixedCustomFee = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.FixedCustomFee").msgclass
  FixedCustomFeeList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.FixedCustomFeeList").msgclass
  FeeExemptKeyList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.FeeExemptKeyList").msgclass
  CustomFeeLimit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CustomFeeLimit").msgclass
end
