# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/duration.proto

require 'google/protobuf'


descriptor_data = "\n\x17services/duration.proto\x12\x05proto\"\x1b\n\x08\x44uration\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  Duration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Duration").msgclass
end
