# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/ethereum_transaction.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n#services/ethereum_transaction.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"m\n\x17\x45thereumTransactionBody\x12\x15\n\rethereum_data\x18\x01 \x01(\x0c\x12 \n\tcall_data\x18\x02 \x01(\x0b\x32\r.proto.FileID\x12\x19\n\x11max_gas_allowance\x18\x03 \x01(\x03\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  EthereumTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.EthereumTransactionBody").msgclass
end
