# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/exchange_rate.proto

require 'google/protobuf'

require 'hiero/proto/services/timestamp_pb'


descriptor_data = "\n\x1cservices/exchange_rate.proto\x12\x05proto\x1a\x18services/timestamp.proto\"e\n\x0c\x45xchangeRate\x12\x11\n\thbarEquiv\x18\x01 \x01(\x05\x12\x11\n\tcentEquiv\x18\x02 \x01(\x05\x12/\n\x0e\x65xpirationTime\x18\x03 \x01(\x0b\x32\x17.proto.TimestampSeconds\"b\n\x0f\x45xchangeRateSet\x12(\n\x0b\x63urrentRate\x18\x01 \x01(\x0b\x32\x13.proto.ExchangeRate\x12%\n\x08nextRate\x18\x02 \x01(\x0b\x32\x13.proto.ExchangeRateB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ExchangeRate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ExchangeRate").msgclass
  ExchangeRateSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ExchangeRateSet").msgclass
end
