# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/file_append.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1aservices/file_append.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"L\n\x19\x46ileAppendTransactionBody\x12\x1d\n\x06\x66ileID\x18\x02 \x01(\x0b\x32\r.proto.FileID\x12\x10\n\x08\x63ontents\x18\x04 \x01(\x0c\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  FileAppendTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.FileAppendTransactionBody").msgclass
end
