# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/file_service.proto

require 'google/protobuf'

require 'hiero/proto/services/query_pb'
require 'hiero/proto/services/response_pb'
require 'hiero/proto/services/transaction_response_pb'
require 'hiero/proto/services/transaction_pb'


descriptor_data = "\n\x1bservices/file_service.proto\x12\x05proto\x1a\x14services/query.proto\x1a\x17services/response.proto\x1a#services/transaction_response.proto\x1a\x1aservices/transaction.proto2\xe9\x03\n\x0b\x46ileService\x12<\n\ncreateFile\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12<\n\nupdateFile\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12<\n\ndeleteFile\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12?\n\rappendContent\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12/\n\x0egetFileContent\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12,\n\x0bgetFileInfo\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12>\n\x0csystemDelete\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12@\n\x0esystemUndelete\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponseB(\n&com.hederahashgraph.service.proto.javab\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
end
