# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/file_get_info.proto

require 'google/protobuf'

require 'hiero/proto/services/timestamp_pb'
require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'


descriptor_data = "\n\x1cservices/file_get_info.proto\x12\x05proto\x1a\x18services/timestamp.proto\x1a\x1aservices/basic_types.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\"U\n\x10\x46ileGetInfoQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12\x1d\n\x06\x66ileID\x18\x02 \x01(\x0b\x32\r.proto.FileID\"\xa7\x02\n\x13\x46ileGetInfoResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12\x35\n\x08\x66ileInfo\x18\x02 \x01(\x0b\x32#.proto.FileGetInfoResponse.FileInfo\x1a\xb1\x01\n\x08\x46ileInfo\x12\x1d\n\x06\x66ileID\x18\x01 \x01(\x0b\x32\r.proto.FileID\x12\x0c\n\x04size\x18\x02 \x01(\x03\x12(\n\x0e\x65xpirationTime\x18\x03 \x01(\x0b\x32\x10.proto.Timestamp\x12\x0f\n\x07\x64\x65leted\x18\x04 \x01(\x08\x12\x1c\n\x04keys\x18\x05 \x01(\x0b\x32\x0e.proto.KeyList\x12\x0c\n\x04memo\x18\x06 \x01(\t\x12\x11\n\tledger_id\x18\x07 \x01(\x0c\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  FileGetInfoQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.FileGetInfoQuery").msgclass
  FileGetInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.FileGetInfoResponse").msgclass
  FileGetInfoResponse::FileInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.FileGetInfoResponse.FileInfo").msgclass
end
