# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/file_delete.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1aservices/file_delete.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\":\n\x19\x46ileDeleteTransactionBody\x12\x1d\n\x06\x66ileID\x18\x02 \x01(\x0b\x32\r.proto.FileIDB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  FileDeleteTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.FileDeleteTransactionBody").msgclass
end
