# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/file_update.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/timestamp_pb'
require 'google/protobuf/wrappers_pb'


descriptor_data = "\n\x1aservices/file_update.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x18services/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xc0\x01\n\x19\x46ileUpdateTransactionBody\x12\x1d\n\x06\x66ileID\x18\x01 \x01(\x0b\x32\r.proto.FileID\x12(\n\x0e\x65xpirationTime\x18\x02 \x01(\x0b\x32\x10.proto.Timestamp\x12\x1c\n\x04keys\x18\x03 \x01(\x0b\x32\x0e.proto.KeyList\x12\x10\n\x08\x63ontents\x18\x04 \x01(\x0c\x12*\n\x04memo\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValueB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  FileUpdateTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.FileUpdateTransactionBody").msgclass
end
