# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/file_get_contents.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'


descriptor_data = "\n services/file_get_contents.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\"Y\n\x14\x46ileGetContentsQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12\x1d\n\x06\x66ileID\x18\x02 \x01(\x0b\x32\r.proto.FileID\"\xc4\x01\n\x17\x46ileGetContentsResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12\x41\n\x0c\x66ileContents\x18\x02 \x01(\x0b\x32+.proto.FileGetContentsResponse.FileContents\x1a?\n\x0c\x46ileContents\x12\x1d\n\x06\x66ileID\x18\x01 \x01(\x0b\x32\r.proto.FileID\x12\x10\n\x08\x63ontents\x18\x02 \x01(\x0c\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  FileGetContentsQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.FileGetContentsQuery").msgclass
  FileGetContentsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.FileGetContentsResponse").msgclass
  FileGetContentsResponse::FileContents = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.FileGetContentsResponse.FileContents").msgclass
end
