# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/freeze_service.proto

require 'google/protobuf'

require 'hiero/proto/services/transaction_response_pb'
require 'hiero/proto/services/transaction_pb'


descriptor_data = "\n\x1dservices/freeze_service.proto\x12\x05proto\x1a#services/transaction_response.proto\x1a\x1aservices/transaction.proto2I\n\rFreezeService\x12\x38\n\x06\x66reeze\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponseB(\n&com.hederahashgraph.service.proto.javab\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
end
