# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/freeze_type.proto

require 'google/protobuf'


descriptor_data = "\n\x1aservices/freeze_type.proto\x12\x05proto*\x88\x01\n\nFreezeType\x12\x17\n\x13UNKNOWN_FREEZE_TYPE\x10\x00\x12\x0f\n\x0b\x46REEZE_ONLY\x10\x01\x12\x13\n\x0fPREPARE_UPGRADE\x10\x02\x12\x12\n\x0e\x46REEZE_UPGRADE\x10\x03\x12\x10\n\x0c\x46REEZE_ABORT\x10\x04\x12\x15\n\x11TELEMETRY_UPGRADE\x10\x05\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  FreezeType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.FreezeType").enummodule
end
