# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/freeze.proto

require 'google/protobuf'

require 'hiero/proto/services/timestamp_pb'
require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/freeze_type_pb'


descriptor_data = "\n\x15services/freeze.proto\x12\x05proto\x1a\x18services/timestamp.proto\x1a\x1aservices/basic_types.proto\x1a\x1aservices/freeze_type.proto\"\xf2\x01\n\x15\x46reezeTransactionBody\x12\x15\n\tstartHour\x18\x01 \x01(\x05\x42\x02\x18\x01\x12\x14\n\x08startMin\x18\x02 \x01(\x05\x42\x02\x18\x01\x12\x13\n\x07\x65ndHour\x18\x03 \x01(\x05\x42\x02\x18\x01\x12\x12\n\x06\x65ndMin\x18\x04 \x01(\x05\x42\x02\x18\x01\x12\"\n\x0bupdate_file\x18\x05 \x01(\x0b\x32\r.proto.FileID\x12\x11\n\tfile_hash\x18\x06 \x01(\x0c\x12$\n\nstart_time\x18\x07 \x01(\x0b\x32\x10.proto.Timestamp\x12&\n\x0b\x66reeze_type\x18\x08 \x01(\x0e\x32\x11.proto.FreezeTypeB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  FreezeTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.FreezeTransactionBody").msgclass
end
