# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/get_by_key.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'
require 'hiero/proto/services/crypto_add_live_hash_pb'


descriptor_data = "\n\x19services/get_by_key.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\x1a#services/crypto_add_live_hash.proto\"P\n\rGetByKeyQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12\x17\n\x03key\x18\x02 \x01(\x0b\x32\n.proto.Key:\x02\x18\x01\"\xae\x01\n\x08\x45ntityID\x12%\n\taccountID\x18\x01 \x01(\x0b\x32\x10.proto.AccountIDH\x00\x12#\n\x08liveHash\x18\x02 \x01(\x0b\x32\x0f.proto.LiveHashH\x00\x12\x1f\n\x06\x66ileID\x18\x03 \x01(\x0b\x32\r.proto.FileIDH\x00\x12\'\n\ncontractID\x18\x04 \x01(\x0b\x32\x11.proto.ContractIDH\x00:\x02\x18\x01\x42\x08\n\x06\x65ntity\"`\n\x10GetByKeyResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12!\n\x08\x65ntities\x18\x02 \x03(\x0b\x32\x0f.proto.EntityID:\x02\x18\x01\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  GetByKeyQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.GetByKeyQuery").msgclass
  EntityID = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.EntityID").msgclass
  GetByKeyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.GetByKeyResponse").msgclass
end
