# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/hook_types.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'google/protobuf/wrappers_pb'


descriptor_data = "\n\x19services/hook_types.proto\x12\x1a\x63om.hedera.hapi.node.hooks\x1a\x1aservices/basic_types.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xab\x01\n\x0cHookCreation\x12&\n\tentity_id\x18\x01 \x01(\x0b\x32\x13.proto.HookEntityId\x12@\n\x07\x64\x65tails\x18\x02 \x01(\x0b\x32/.com.hedera.hapi.node.hooks.HookCreationDetails\x12\x31\n\x0cnext_hook_id\x18\t \x01(\x0b\x32\x1b.google.protobuf.Int64Value\"\xcf\x01\n\x13HookCreationDetails\x12G\n\x0f\x65xtension_point\x18\x01 \x01(\x0e\x32..com.hedera.hapi.node.hooks.HookExtensionPoint\x12\x0f\n\x07hook_id\x18\x02 \x01(\x03\x12\x37\n\x08\x65vm_hook\x18\x03 \x01(\x0b\x32#.com.hedera.hapi.node.hooks.EvmHookH\x00\x12\x1d\n\tadmin_key\x18\x04 \x01(\x0b\x32\n.proto.KeyB\x06\n\x04hook\"\x8b\x01\n\x07\x45vmHook\x12\x35\n\x04spec\x18\x01 \x01(\x0b\x32\'.com.hedera.hapi.node.hooks.EvmHookSpec\x12I\n\x0fstorage_updates\x18\x02 \x03(\x0b\x32\x30.com.hedera.hapi.node.hooks.EvmHookStorageUpdate\"J\n\x0b\x45vmHookSpec\x12(\n\x0b\x63ontract_id\x18\x01 \x01(\x0b\x32\x11.proto.ContractIDH\x00\x42\x11\n\x0f\x62ytecode_source\"\xb6\x01\n\x14\x45vmHookStorageUpdate\x12\x46\n\x0cstorage_slot\x18\x01 \x01(\x0b\x32..com.hedera.hapi.node.hooks.EvmHookStorageSlotH\x00\x12L\n\x0fmapping_entries\x18\x02 \x01(\x0b\x32\x31.com.hedera.hapi.node.hooks.EvmHookMappingEntriesH\x00\x42\x08\n\x06update\"o\n\x15\x45vmHookMappingEntries\x12\x14\n\x0cmapping_slot\x18\x01 \x01(\x0c\x12@\n\x07\x65ntries\x18\x02 \x03(\x0b\x32/.com.hedera.hapi.node.hooks.EvmHookMappingEntry\"T\n\x13\x45vmHookMappingEntry\x12\r\n\x03key\x18\x01 \x01(\x0cH\x00\x12\x12\n\x08preimage\x18\x02 \x01(\x0cH\x00\x12\r\n\x05value\x18\x03 \x01(\x0c\x42\x0b\n\tentry_key\"0\n\x12\x45vmHookStorageSlot\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c*0\n\x12HookExtensionPoint\x12\x1a\n\x16\x41\x43\x43OUNT_ALLOWANCE_HOOK\x10\x00\x42%\n!com.hedera.hapi.node.hooks.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module Hooks
          HookCreation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.hooks.HookCreation").msgclass
          HookCreationDetails = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.hooks.HookCreationDetails").msgclass
          EvmHook = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.hooks.EvmHook").msgclass
          EvmHookSpec = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.hooks.EvmHookSpec").msgclass
          EvmHookStorageUpdate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.hooks.EvmHookStorageUpdate").msgclass
          EvmHookMappingEntries = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.hooks.EvmHookMappingEntries").msgclass
          EvmHookMappingEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.hooks.EvmHookMappingEntry").msgclass
          EvmHookStorageSlot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.hooks.EvmHookStorageSlot").msgclass
          HookExtensionPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.hooks.HookExtensionPoint").enummodule
        end
      end
    end
  end
end
