# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/hook_store.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/hook_types_pb'


descriptor_data = "\n\x19services/hook_store.proto\x12\x1a\x63om.hedera.hapi.node.hooks\x1a\x1aservices/basic_types.proto\x1a\x19services/hook_types.proto\"\x85\x01\n\x18HookStoreTransactionBody\x12\x1e\n\x07hook_id\x18\x01 \x01(\x0b\x32\r.proto.HookId\x12I\n\x0fstorage_updates\x18\x02 \x03(\x0b\x32\x30.com.hedera.hapi.node.hooks.EvmHookStorageUpdateB%\n!com.hedera.hapi.node.hooks.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module Hooks
          HookStoreTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.hooks.HookStoreTransactionBody").msgclass
        end
      end
    end
  end
end
