# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/hook_dispatch.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/hook_types_pb'


descriptor_data = "\n\x1cservices/hook_dispatch.proto\x12\x1a\x63om.hedera.hapi.node.hooks\x1a\x1aservices/basic_types.proto\x1a\x19services/hook_types.proto\"\xd1\x01\n\x1bHookDispatchTransactionBody\x12*\n\x11hook_id_to_delete\x18\x01 \x01(\x0b\x32\r.proto.HookIdH\x00\x12<\n\x08\x63reation\x18\x02 \x01(\x0b\x32(.com.hedera.hapi.node.hooks.HookCreationH\x00\x12>\n\texecution\x18\x03 \x01(\x0b\x32).com.hedera.hapi.node.hooks.HookExecutionH\x00\x42\x08\n\x06\x61\x63tion\"[\n\rHookExecution\x12+\n\x0ehook_entity_id\x18\x01 \x01(\x0b\x32\x13.proto.HookEntityId\x12\x1d\n\x04\x63\x61ll\x18\x02 \x01(\x0b\x32\x0f.proto.HookCallB%\n!com.hedera.hapi.node.hooks.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module Hooks
          HookDispatchTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.hooks.HookDispatchTransactionBody").msgclass
          HookExecution = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.hooks.HookExecution").msgclass
        end
      end
    end
  end
end
