# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/network_get_version_info.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'


descriptor_data = "\n\'services/network_get_version_info.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\"@\n\x1aNetworkGetVersionInfoQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\"\xaf\x01\n\x1dNetworkGetVersionInfoResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12\x30\n\x10hapiProtoVersion\x18\x02 \x01(\x0b\x32\x16.proto.SemanticVersion\x12\x35\n\x15hederaServicesVersion\x18\x03 \x01(\x0b\x32\x16.proto.SemanticVersionB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  NetworkGetVersionInfoQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NetworkGetVersionInfoQuery").msgclass
  NetworkGetVersionInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NetworkGetVersionInfoResponse").msgclass
end
