# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/network_get_execution_time.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'


descriptor_data = "\n)services/network_get_execution_time.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\"u\n\x1cNetworkGetExecutionTimeQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12-\n\x0ftransaction_ids\x18\x02 \x03(\x0b\x32\x14.proto.TransactionID:\x02\x18\x01\"e\n\x1fNetworkGetExecutionTimeResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12\x17\n\x0f\x65xecution_times\x18\x02 \x03(\x04:\x02\x18\x01\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  NetworkGetExecutionTimeQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NetworkGetExecutionTimeQuery").msgclass
  NetworkGetExecutionTimeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NetworkGetExecutionTimeResponse").msgclass
end
