# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/node_create.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1aservices/node_create.proto\x12 com.hedera.hapi.node.addressbook\x1a\x1aservices/basic_types.proto\"\x87\x03\n\x19NodeCreateTransactionBody\x12$\n\naccount_id\x18\x01 \x01(\x0b\x32\x10.proto.AccountID\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12/\n\x0fgossip_endpoint\x18\x03 \x03(\x0b\x32\x16.proto.ServiceEndpoint\x12\x30\n\x10service_endpoint\x18\x04 \x03(\x0b\x32\x16.proto.ServiceEndpoint\x12\x1d\n\x15gossip_ca_certificate\x18\x05 \x01(\x0c\x12\x1d\n\x15grpc_certificate_hash\x18\x06 \x01(\x0c\x12\x1d\n\tadmin_key\x18\x07 \x01(\x0b\x32\n.proto.Key\x12\x16\n\x0e\x64\x65\x63line_reward\x18\x08 \x01(\x08\x12\x33\n\x13grpc_proxy_endpoint\x18\t \x01(\x0b\x32\x16.proto.ServiceEndpoint\x12\"\n\x1a\x61ssociated_registered_node\x18\n \x03(\x04\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module Addressbook
          NodeCreateTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.addressbook.NodeCreateTransactionBody").msgclass
        end
      end
    end
  end
end
