# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/node_delete.proto

require 'google/protobuf'


descriptor_data = "\n\x1aservices/node_delete.proto\x12 com.hedera.hapi.node.addressbook\",\n\x19NodeDeleteTransactionBody\x12\x0f\n\x07node_id\x18\x01 \x01(\x04\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module Addressbook
          NodeDeleteTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.addressbook.NodeDeleteTransactionBody").msgclass
        end
      end
    end
  end
end
