# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/node_update.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'
require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1aservices/node_update.proto\x12 com.hedera.hapi.node.addressbook\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1aservices/basic_types.proto\"\xd1\x04\n\x19NodeUpdateTransactionBody\x12\x0f\n\x07node_id\x18\x01 \x01(\x04\x12$\n\naccount_id\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12\x31\n\x0b\x64\x65scription\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12/\n\x0fgossip_endpoint\x18\x04 \x03(\x0b\x32\x16.proto.ServiceEndpoint\x12\x30\n\x10service_endpoint\x18\x05 \x03(\x0b\x32\x16.proto.ServiceEndpoint\x12:\n\x15gossip_ca_certificate\x18\x06 \x01(\x0b\x32\x1b.google.protobuf.BytesValue\x12:\n\x15grpc_certificate_hash\x18\x07 \x01(\x0b\x32\x1b.google.protobuf.BytesValue\x12\x1d\n\tadmin_key\x18\x08 \x01(\x0b\x32\n.proto.Key\x12\x32\n\x0e\x64\x65\x63line_reward\x18\t \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x33\n\x13grpc_proxy_endpoint\x18\n \x01(\x0b\x32\x16.proto.ServiceEndpoint\x12g\n\x1f\x61ssociated_registered_node_list\x18\x0b \x01(\x0b\x32>.com.hedera.hapi.node.addressbook.AssociatedRegisteredNodeList\"B\n\x1c\x41ssociatedRegisteredNodeList\x12\"\n\x1a\x61ssociated_registered_node\x18\x01 \x03(\x04\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module Addressbook
          NodeUpdateTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.addressbook.NodeUpdateTransactionBody").msgclass
          AssociatedRegisteredNodeList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.addressbook.AssociatedRegisteredNodeList").msgclass
        end
      end
    end
  end
end
