# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/query_header.proto

require 'google/protobuf'

require 'hiero/proto/services/transaction_pb'


descriptor_data = "\n\x1bservices/query_header.proto\x12\x05proto\x1a\x1aservices/transaction.proto\"]\n\x0bQueryHeader\x12#\n\x07payment\x18\x01 \x01(\x0b\x32\x12.proto.Transaction\x12)\n\x0cresponseType\x18\x02 \x01(\x0e\x32\x13.proto.ResponseType*e\n\x0cResponseType\x12\x0f\n\x0b\x41NSWER_ONLY\x10\x00\x12\x16\n\x12\x41NSWER_STATE_PROOF\x10\x01\x12\x0f\n\x0b\x43OST_ANSWER\x10\x02\x12\x1b\n\x17\x43OST_ANSWER_STATE_PROOF\x10\x03\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  QueryHeader = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.QueryHeader").msgclass
  ResponseType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ResponseType").enummodule
end
