# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/registered_service_endpoint.proto

require 'google/protobuf'


descriptor_data = "\n*services/registered_service_endpoint.proto\x12 com.hedera.hapi.node.addressbook\"\xe2\x06\n\x19RegisteredServiceEndpoint\x12\x14\n\nip_address\x18\x01 \x01(\x0cH\x00\x12\x15\n\x0b\x64omain_name\x18\x02 \x01(\tH\x00\x12\x0c\n\x04port\x18\x03 \x01(\r\x12\x14\n\x0crequires_tls\x18\x04 \x01(\x08\x12\x63\n\nblock_node\x18\x05 \x01(\x0b\x32M.com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.BlockNodeEndpointH\x01\x12\x65\n\x0bmirror_node\x18\x06 \x01(\x0b\x32N.com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.MirrorNodeEndpointH\x01\x12\x61\n\trpc_relay\x18\x07 \x01(\x0b\x32L.com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.RpcRelayEndpointH\x01\x12m\n\x0fgeneral_service\x18\x08 \x01(\x0b\x32R.com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.GeneralServiceEndpointH\x01\x1a\xe0\x01\n\x11\x42lockNodeEndpoint\x12p\n\x0c\x65ndpoint_api\x18\x01 \x03(\x0e\x32Z.com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.BlockNodeEndpoint.BlockNodeApi\"Y\n\x0c\x42lockNodeApi\x12\t\n\x05OTHER\x10\x00\x12\n\n\x06STATUS\x10\x01\x12\x0b\n\x07PUBLISH\x10\x02\x12\x14\n\x10SUBSCRIBE_STREAM\x10\x03\x12\x0f\n\x0bSTATE_PROOF\x10\x04\x1a\x14\n\x12MirrorNodeEndpoint\x1a\x12\n\x10RpcRelayEndpoint\x1a-\n\x16GeneralServiceEndpoint\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\tB\t\n\x07\x61\x64\x64ressB\x0f\n\rendpoint_typeB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module Addressbook
          RegisteredServiceEndpoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint").msgclass
          RegisteredServiceEndpoint::BlockNodeEndpoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.BlockNodeEndpoint").msgclass
          RegisteredServiceEndpoint::BlockNodeEndpoint::BlockNodeApi = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.BlockNodeEndpoint.BlockNodeApi").enummodule
          RegisteredServiceEndpoint::MirrorNodeEndpoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.MirrorNodeEndpoint").msgclass
          RegisteredServiceEndpoint::RpcRelayEndpoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.RpcRelayEndpoint").msgclass
          RegisteredServiceEndpoint::GeneralServiceEndpoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.GeneralServiceEndpoint").msgclass
        end
      end
    end
  end
end
