# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/registered_node_delete.proto

require 'google/protobuf'


descriptor_data = "\n%services/registered_node_delete.proto\x12 com.hedera.hapi.node.addressbook\"A\n#RegisteredNodeDeleteTransactionBody\x12\x1a\n\x12registered_node_id\x18\x01 \x01(\x04\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module Addressbook
          RegisteredNodeDeleteTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.addressbook.RegisteredNodeDeleteTransactionBody").msgclass
        end
      end
    end
  end
end
