# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/response_header.proto

require 'google/protobuf'

require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_code_pb'


descriptor_data = "\n\x1eservices/response_header.proto\x12\x05proto\x1a\x1bservices/query_header.proto\x1a\x1cservices/response_code.proto\"\x9b\x01\n\x0eResponseHeader\x12<\n\x1bnodeTransactionPrecheckCode\x18\x01 \x01(\x0e\x32\x17.proto.ResponseCodeEnum\x12)\n\x0cresponseType\x18\x02 \x01(\x0e\x32\x13.proto.ResponseType\x12\x0c\n\x04\x63ost\x18\x03 \x01(\x04\x12\x12\n\nstateProof\x18\x04 \x01(\x0c\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ResponseHeader = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ResponseHeader").msgclass
end
