# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/schedule_sign.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1cservices/schedule_sign.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"D\n\x1bScheduleSignTransactionBody\x12%\n\nscheduleID\x18\x01 \x01(\x0b\x32\x11.proto.ScheduleIDB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ScheduleSignTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ScheduleSignTransactionBody").msgclass
end
