# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/schedule_service.proto

require 'google/protobuf'

require 'hiero/proto/services/query_pb'
require 'hiero/proto/services/response_pb'
require 'hiero/proto/services/transaction_response_pb'
require 'hiero/proto/services/transaction_pb'


descriptor_data = "\n\x1fservices/schedule_service.proto\x12\x05proto\x1a\x14services/query.proto\x1a\x17services/response.proto\x1a#services/transaction_response.proto\x1a\x1aservices/transaction.proto2\x87\x02\n\x0fScheduleService\x12@\n\x0e\x63reateSchedule\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12>\n\x0csignSchedule\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12@\n\x0e\x64\x65leteSchedule\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12\x30\n\x0fgetScheduleInfo\x12\x0c.proto.Query\x1a\x0f.proto.ResponseB(\n&com.hederahashgraph.service.proto.javab\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
end
