# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/schedule_create.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/timestamp_pb'
require 'hiero/proto/services/schedulable_transaction_body_pb'


descriptor_data = "\n\x1eservices/schedule_create.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x18services/timestamp.proto\x1a+services/schedulable_transaction_body.proto\"\xfe\x01\n\x1dScheduleCreateTransactionBody\x12\x43\n\x18scheduledTransactionBody\x18\x01 \x01(\x0b\x32!.proto.SchedulableTransactionBody\x12\x0c\n\x04memo\x18\x02 \x01(\t\x12\x1c\n\x08\x61\x64minKey\x18\x03 \x01(\x0b\x32\n.proto.Key\x12(\n\x0epayerAccountID\x18\x04 \x01(\x0b\x32\x10.proto.AccountID\x12)\n\x0f\x65xpiration_time\x18\x05 \x01(\x0b\x32\x10.proto.Timestamp\x12\x17\n\x0fwait_for_expiry\x18\r \x01(\x08\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ScheduleCreateTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ScheduleCreateTransactionBody").msgclass
end
