# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/schedule_get_info.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/timestamp_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'
require 'hiero/proto/services/schedulable_transaction_body_pb'


descriptor_data = "\n services/schedule_get_info.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x18services/timestamp.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\x1a+services/schedulable_transaction_body.proto\"a\n\x14ScheduleGetInfoQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12%\n\nscheduleID\x18\x02 \x01(\x0b\x32\x11.proto.ScheduleID\"\x88\x04\n\x0cScheduleInfo\x12%\n\nscheduleID\x18\x01 \x01(\x0b\x32\x11.proto.ScheduleID\x12)\n\rdeletion_time\x18\x02 \x01(\x0b\x32\x10.proto.TimestampH\x00\x12*\n\x0e\x65xecution_time\x18\x03 \x01(\x0b\x32\x10.proto.TimestampH\x00\x12(\n\x0e\x65xpirationTime\x18\x04 \x01(\x0b\x32\x10.proto.Timestamp\x12\x43\n\x18scheduledTransactionBody\x18\x05 \x01(\x0b\x32!.proto.SchedulableTransactionBody\x12\x0c\n\x04memo\x18\x06 \x01(\t\x12\x1c\n\x08\x61\x64minKey\x18\x07 \x01(\x0b\x32\n.proto.Key\x12\x1f\n\x07signers\x18\x08 \x01(\x0b\x32\x0e.proto.KeyList\x12*\n\x10\x63reatorAccountID\x18\t \x01(\x0b\x32\x10.proto.AccountID\x12(\n\x0epayerAccountID\x18\n \x01(\x0b\x32\x10.proto.AccountID\x12\x34\n\x16scheduledTransactionID\x18\x0b \x01(\x0b\x32\x14.proto.TransactionID\x12\x11\n\tledger_id\x18\x0c \x01(\x0c\x12\x17\n\x0fwait_for_expiry\x18\r \x01(\x08\x42\x06\n\x04\x64\x61ta\"k\n\x17ScheduleGetInfoResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12)\n\x0cscheduleInfo\x18\x02 \x01(\x0b\x32\x13.proto.ScheduleInfoB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ScheduleGetInfoQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ScheduleGetInfoQuery").msgclass
  ScheduleInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ScheduleInfo").msgclass
  ScheduleGetInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ScheduleGetInfoResponse").msgclass
end
