# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/smart_contract_service.proto

require 'google/protobuf'

require 'hiero/proto/services/transaction_response_pb'
require 'hiero/proto/services/query_pb'
require 'hiero/proto/services/response_pb'
require 'hiero/proto/services/transaction_pb'


descriptor_data = "\n%services/smart_contract_service.proto\x12\x05proto\x1a#services/transaction_response.proto\x1a\x14services/query.proto\x1a\x17services/response.proto\x1a\x1aservices/transaction.proto2\xc3\x06\n\x14SmartContractService\x12@\n\x0e\x63reateContract\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12@\n\x0eupdateContract\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12\x44\n\x12\x63ontractCallMethod\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12\x38\n\x17\x63ontractCallLocalMethod\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12\x30\n\x0fgetContractInfo\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12\x34\n\x13\x43ontractGetBytecode\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12\x35\n\x0fgetBySolidityID\x12\x0c.proto.Query\x1a\x0f.proto.Response\"\x03\x88\x02\x01\x12=\n\x17getTxRecordByContractID\x12\x0c.proto.Query\x1a\x0f.proto.Response\"\x03\x88\x02\x01\x12@\n\x0e\x64\x65leteContract\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12\x43\n\x0csystemDelete\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\"\x03\x88\x02\x01\x12\x45\n\x0esystemUndelete\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\"\x03\x88\x02\x01\x12>\n\x0c\x63\x61llEthereum\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12;\n\thookStore\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponseB(\n&com.hederahashgraph.service.proto.javab\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
end
