# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/system_undelete.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1eservices/system_undelete.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"o\n\x1dSystemUndeleteTransactionBody\x12\x1f\n\x06\x66ileID\x18\x01 \x01(\x0b\x32\r.proto.FileIDH\x00\x12\'\n\ncontractID\x18\x02 \x01(\x0b\x32\x11.proto.ContractIDH\x00\x42\x04\n\x02idB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  SystemUndeleteTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SystemUndeleteTransactionBody").msgclass
end
