# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/throttle_definitions.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n#services/throttle_definitions.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"W\n\rThrottleGroup\x12.\n\noperations\x18\x01 \x03(\x0e\x32\x1a.proto.HederaFunctionality\x12\x16\n\x0emilliOpsPerSec\x18\x02 \x01(\x04\"x\n\x0eThrottleBucket\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rburstPeriodMs\x18\x02 \x01(\x04\x12,\n\x0ethrottleGroups\x18\x03 \x03(\x0b\x32\x14.proto.ThrottleGroup\x12\x13\n\x0bhigh_volume\x18\x04 \x01(\x08\"E\n\x13ThrottleDefinitions\x12.\n\x0fthrottleBuckets\x18\x01 \x03(\x0b\x32\x15.proto.ThrottleBucketB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  ThrottleGroup = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ThrottleGroup").msgclass
  ThrottleBucket = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ThrottleBucket").msgclass
  ThrottleDefinitions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ThrottleDefinitions").msgclass
end
