# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/timestamp.proto

require 'google/protobuf'


descriptor_data = "\n\x18services/timestamp.proto\x12\x05proto\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"#\n\x10TimestampSeconds\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  Timestamp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Timestamp").msgclass
  TimestampSeconds = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TimestampSeconds").msgclass
end
