# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/token_airdrop.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1cservices/token_airdrop.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"P\n\x1bTokenAirdropTransactionBody\x12\x31\n\x0ftoken_transfers\x18\x01 \x03(\x0b\x32\x18.proto.TokenTransferListB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TokenAirdropTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenAirdropTransactionBody").msgclass
end
