# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/token_update.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/duration_pb'
require 'hiero/proto/services/timestamp_pb'
require 'google/protobuf/wrappers_pb'


descriptor_data = "\n\x1bservices/token_update.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x17services/duration.proto\x1a\x18services/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x86\x05\n\x1aTokenUpdateTransactionBody\x12\x1d\n\x05token\x18\x01 \x01(\x0b\x32\x0e.proto.TokenID\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\"\n\x08treasury\x18\x04 \x01(\x0b\x32\x10.proto.AccountID\x12\x1c\n\x08\x61\x64minKey\x18\x05 \x01(\x0b\x32\n.proto.Key\x12\x1a\n\x06kycKey\x18\x06 \x01(\x0b\x32\n.proto.Key\x12\x1d\n\tfreezeKey\x18\x07 \x01(\x0b\x32\n.proto.Key\x12\x1b\n\x07wipeKey\x18\x08 \x01(\x0b\x32\n.proto.Key\x12\x1d\n\tsupplyKey\x18\t \x01(\x0b\x32\n.proto.Key\x12*\n\x10\x61utoRenewAccount\x18\n \x01(\x0b\x32\x10.proto.AccountID\x12(\n\x0f\x61utoRenewPeriod\x18\x0b \x01(\x0b\x32\x0f.proto.Duration\x12 \n\x06\x65xpiry\x18\x0c \x01(\x0b\x32\x10.proto.Timestamp\x12*\n\x04memo\x18\r \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12$\n\x10\x66\x65\x65_schedule_key\x18\x0e \x01(\x0b\x32\n.proto.Key\x12\x1d\n\tpause_key\x18\x0f \x01(\x0b\x32\n.proto.Key\x12-\n\x08metadata\x18\x10 \x01(\x0b\x32\x1b.google.protobuf.BytesValue\x12 \n\x0cmetadata_key\x18\x11 \x01(\x0b\x32\n.proto.Key\x12\x38\n\x15key_verification_mode\x18\x12 \x01(\x0e\x32\x19.proto.TokenKeyValidationB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TokenUpdateTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenUpdateTransactionBody").msgclass
end
