# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/token_update_nfts.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'google/protobuf/wrappers_pb'


descriptor_data = "\n services/token_update_nfts.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x86\x01\n\x1eTokenUpdateNftsTransactionBody\x12\x1d\n\x05token\x18\x01 \x01(\x0b\x32\x0e.proto.TokenID\x12\x16\n\x0eserial_numbers\x18\x02 \x03(\x03\x12-\n\x08metadata\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.BytesValueB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TokenUpdateNftsTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenUpdateNftsTransactionBody").msgclass
end
