# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/token_revoke_kyc.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1fservices/token_revoke_kyc.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"a\n\x1dTokenRevokeKycTransactionBody\x12\x1d\n\x05token\x18\x01 \x01(\x0b\x32\x0e.proto.TokenID\x12!\n\x07\x61\x63\x63ount\x18\x02 \x01(\x0b\x32\x10.proto.AccountIDB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TokenRevokeKycTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenRevokeKycTransactionBody").msgclass
end
