# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/token_get_account_nft_infos.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/token_get_nft_info_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'


descriptor_data = "\n*services/token_get_account_nft_infos.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a!services/token_get_nft_info.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\"\x83\x01\n\x1cTokenGetAccountNftInfosQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12#\n\taccountID\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12\r\n\x05start\x18\x03 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x04 \x01(\x03\"k\n\x1fTokenGetAccountNftInfosResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12!\n\x04nfts\x18\x02 \x03(\x0b\x32\x13.proto.TokenNftInfoB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TokenGetAccountNftInfosQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenGetAccountNftInfosQuery").msgclass
  TokenGetAccountNftInfosResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenGetAccountNftInfosResponse").msgclass
end
