# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/token_burn.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x19services/token_burn.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"`\n\x18TokenBurnTransactionBody\x12\x1d\n\x05token\x18\x01 \x01(\x0b\x32\x0e.proto.TokenID\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x04\x12\x15\n\rserialNumbers\x18\x03 \x03(\x03\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TokenBurnTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenBurnTransactionBody").msgclass
end
