# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/token_delete.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1bservices/token_delete.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\";\n\x1aTokenDeleteTransactionBody\x12\x1d\n\x05token\x18\x01 \x01(\x0b\x32\x0e.proto.TokenIDB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TokenDeleteTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenDeleteTransactionBody").msgclass
end
