# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/token_wipe_account.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n!services/token_wipe_account.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"\x8a\x01\n\x1fTokenWipeAccountTransactionBody\x12\x1d\n\x05token\x18\x01 \x01(\x0b\x32\x0e.proto.TokenID\x12!\n\x07\x61\x63\x63ount\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x04\x12\x15\n\rserialNumbers\x18\x04 \x03(\x03\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TokenWipeAccountTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenWipeAccountTransactionBody").msgclass
end
