# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/token_reject.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1bservices/token_reject.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"h\n\x1aTokenRejectTransactionBody\x12\x1f\n\x05owner\x18\x01 \x01(\x0b\x32\x10.proto.AccountID\x12)\n\nrejections\x18\x02 \x03(\x0b\x32\x15.proto.TokenReference\"k\n\x0eTokenReference\x12(\n\x0e\x66ungible_token\x18\x01 \x01(\x0b\x32\x0e.proto.TokenIDH\x00\x12\x1b\n\x03nft\x18\x02 \x01(\x0b\x32\x0c.proto.NftIDH\x00\x42\x12\n\x10token_identifierB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TokenRejectTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenRejectTransactionBody").msgclass
  TokenReference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenReference").msgclass
end
