# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/token_fee_schedule_update.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/custom_fees_pb'


descriptor_data = "\n(services/token_fee_schedule_update.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1aservices/custom_fees.proto\"p\n%TokenFeeScheduleUpdateTransactionBody\x12 \n\x08token_id\x18\x01 \x01(\x0b\x32\x0e.proto.TokenID\x12%\n\x0b\x63ustom_fees\x18\x02 \x03(\x0b\x32\x10.proto.CustomFeeB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TokenFeeScheduleUpdateTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenFeeScheduleUpdateTransactionBody").msgclass
end
