# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/token_cancel_airdrop.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n#services/token_cancel_airdrop.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"V\n!TokenCancelAirdropTransactionBody\x12\x31\n\x10pending_airdrops\x18\x01 \x03(\x0b\x32\x17.proto.PendingAirdropIdB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TokenCancelAirdropTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenCancelAirdropTransactionBody").msgclass
end
