# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/token_dissociate.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1fservices/token_dissociate.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"c\n\x1eTokenDissociateTransactionBody\x12!\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x10.proto.AccountID\x12\x1e\n\x06tokens\x18\x02 \x03(\x0b\x32\x0e.proto.TokenIDB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TokenDissociateTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenDissociateTransactionBody").msgclass
end
