# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/token_get_nft_info.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'
require 'hiero/proto/services/timestamp_pb'


descriptor_data = "\n!services/token_get_nft_info.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\x1a\x18services/timestamp.proto\"W\n\x14TokenGetNftInfoQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12\x1b\n\x05nftID\x18\x02 \x01(\x0b\x32\x0c.proto.NftID\"\xc3\x01\n\x0cTokenNftInfo\x12\x1b\n\x05nftID\x18\x01 \x01(\x0b\x32\x0c.proto.NftID\x12#\n\taccountID\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12&\n\x0c\x63reationTime\x18\x03 \x01(\x0b\x32\x10.proto.Timestamp\x12\x10\n\x08metadata\x18\x04 \x01(\x0c\x12\x11\n\tledger_id\x18\x05 \x01(\x0c\x12$\n\nspender_id\x18\x06 \x01(\x0b\x32\x10.proto.AccountID\"b\n\x17TokenGetNftInfoResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12 \n\x03nft\x18\x02 \x01(\x0b\x32\x13.proto.TokenNftInfoB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TokenGetNftInfoQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenGetNftInfoQuery").msgclass
  TokenNftInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenNftInfo").msgclass
  TokenGetNftInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TokenGetNftInfoResponse").msgclass
end
