# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/transaction_get_fast_record.proto

require 'google/protobuf'

require 'hiero/proto/services/transaction_record_pb'
require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'


descriptor_data = "\n*services/transaction_get_fast_record.proto\x12\x05proto\x1a!services/transaction_record.proto\x1a\x1aservices/basic_types.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\"t\n\x1dTransactionGetFastRecordQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12+\n\rtransactionID\x18\x02 \x01(\x0b\x32\x14.proto.TransactionID:\x02\x18\x01\"\x82\x01\n TransactionGetFastRecordResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12\x33\n\x11transactionRecord\x18\x02 \x01(\x0b\x32\x18.proto.TransactionRecord:\x02\x18\x01\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TransactionGetFastRecordQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TransactionGetFastRecordQuery").msgclass
  TransactionGetFastRecordResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TransactionGetFastRecordResponse").msgclass
end
