# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/transaction_get_record.proto

require 'google/protobuf'

require 'hiero/proto/services/transaction_record_pb'
require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'


descriptor_data = "\n%services/transaction_get_record.proto\x12\x05proto\x1a!services/transaction_record.proto\x1a\x1aservices/basic_types.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\"\xa6\x01\n\x19TransactionGetRecordQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12+\n\rtransactionID\x18\x02 \x01(\x0b\x32\x14.proto.TransactionID\x12\x19\n\x11includeDuplicates\x18\x03 \x01(\x08\x12\x1d\n\x15include_child_records\x18\x04 \x01(\x08\"\xf6\x01\n\x1cTransactionGetRecordResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12\x33\n\x11transactionRecord\x18\x03 \x01(\x0b\x32\x18.proto.TransactionRecord\x12=\n\x1b\x64uplicateTransactionRecords\x18\x04 \x03(\x0b\x32\x18.proto.TransactionRecord\x12;\n\x19\x63hild_transaction_records\x18\x05 \x03(\x0b\x32\x18.proto.TransactionRecordB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TransactionGetRecordQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TransactionGetRecordQuery").msgclass
  TransactionGetRecordResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TransactionGetRecordResponse").msgclass
end
