# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/transaction_contents.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n#services/transaction_contents.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"}\n\x11SignedTransaction\x12\x11\n\tbodyBytes\x18\x01 \x01(\x0c\x12#\n\x06sigMap\x18\x02 \x01(\x0b\x32\x13.proto.SignatureMap\x12\x30\n(use_serialized_tx_message_hash_algorithm\x18\x03 \x01(\x08\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  SignedTransaction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SignedTransaction").msgclass
end
