# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/transaction_receipt.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/response_code_pb'
require 'hiero/proto/services/exchange_rate_pb'
require 'google/protobuf/wrappers_pb'


descriptor_data = "\n\"services/transaction_receipt.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a\x1cservices/response_code.proto\x1a\x1cservices/exchange_rate.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xdd\x04\n\x12TransactionReceipt\x12\'\n\x06status\x18\x01 \x01(\x0e\x32\x17.proto.ResponseCodeEnum\x12#\n\taccountID\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12\x1d\n\x06\x66ileID\x18\x03 \x01(\x0b\x32\r.proto.FileID\x12%\n\ncontractID\x18\x04 \x01(\x0b\x32\x11.proto.ContractID\x12,\n\x0c\x65xchangeRate\x18\x05 \x01(\x0b\x32\x16.proto.ExchangeRateSet\x12\x1f\n\x07topicID\x18\x06 \x01(\x0b\x32\x0e.proto.TopicID\x12\x1b\n\x13topicSequenceNumber\x18\x07 \x01(\x04\x12\x18\n\x10topicRunningHash\x18\x08 \x01(\x0c\x12\x1f\n\x17topicRunningHashVersion\x18\t \x01(\x04\x12\x1f\n\x07tokenID\x18\n \x01(\x0b\x32\x0e.proto.TokenID\x12\x16\n\x0enewTotalSupply\x18\x0b \x01(\x04\x12%\n\nscheduleID\x18\x0c \x01(\x0b\x32\x11.proto.ScheduleID\x12\x34\n\x16scheduledTransactionID\x18\r \x01(\x0b\x32\x14.proto.TransactionID\x12\x15\n\rserialNumbers\x18\x0e \x03(\x03\x12\x0f\n\x07node_id\x18\x0f \x01(\x04\x12\x1a\n\x12registered_node_id\x18\x10 \x01(\x04\x12\x32\n\x0c\x62lock_number\x18\x11 \x01(\x0b\x32\x1c.google.protobuf.UInt64ValueB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TransactionReceipt = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TransactionReceipt").msgclass
end
