# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/transaction_response.proto

require 'google/protobuf'

require 'hiero/proto/services/response_code_pb'


descriptor_data = "\n#services/transaction_response.proto\x12\x05proto\x1a\x1cservices/response_code.proto\"a\n\x13TransactionResponse\x12<\n\x1bnodeTransactionPrecheckCode\x18\x01 \x01(\x0e\x32\x17.proto.ResponseCodeEnum\x12\x0c\n\x04\x63ost\x18\x02 \x01(\x04\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TransactionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TransactionResponse").msgclass
end
