# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/transaction_get_receipt.proto

require 'google/protobuf'

require 'hiero/proto/services/transaction_receipt_pb'
require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/query_header_pb'
require 'hiero/proto/services/response_header_pb'


descriptor_data = "\n&services/transaction_get_receipt.proto\x12\x05proto\x1a\"services/transaction_receipt.proto\x1a\x1aservices/basic_types.proto\x1a\x1bservices/query_header.proto\x1a\x1eservices/response_header.proto\"\xa8\x01\n\x1aTransactionGetReceiptQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12+\n\rtransactionID\x18\x02 \x01(\x0b\x32\x14.proto.TransactionID\x12\x19\n\x11includeDuplicates\x18\x03 \x01(\x08\x12\x1e\n\x16include_child_receipts\x18\x04 \x01(\x08\"\xf2\x01\n\x1dTransactionGetReceiptResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12*\n\x07receipt\x18\x02 \x01(\x0b\x32\x19.proto.TransactionReceipt\x12?\n\x1c\x64uplicateTransactionReceipts\x18\x04 \x03(\x0b\x32\x19.proto.TransactionReceipt\x12=\n\x1a\x63hild_transaction_receipts\x18\x05 \x03(\x0b\x32\x19.proto.TransactionReceiptB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TransactionGetReceiptQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TransactionGetReceiptQuery").msgclass
  TransactionGetReceiptResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TransactionGetReceiptResponse").msgclass
end
