# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/unchecked_submit.proto

require 'google/protobuf'


descriptor_data = "\n\x1fservices/unchecked_submit.proto\x12\x05proto\"3\n\x13UncheckedSubmitBody\x12\x18\n\x10transactionBytes\x18\x01 \x01(\x0c:\x02\x18\x01\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  UncheckedSubmitBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.UncheckedSubmitBody").msgclass
end
