# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/util_prng.proto

require 'google/protobuf'


descriptor_data = "\n\x18services/util_prng.proto\x12\x05proto\"(\n\x17UtilPrngTransactionBody\x12\r\n\x05range\x18\x01 \x01(\x05\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  UtilPrngTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.UtilPrngTransactionBody").msgclass
end
