# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/block_proof.proto

require 'google/protobuf'

require 'hiero/proto/block/stream/signed_record_file_proof_pb'
require 'hiero/proto/block/stream/state_proof_pb'
require 'hiero/proto/block/stream/tss_signed_block_proof_pb'


descriptor_data = "\n\x1e\x62lock/stream/block_proof.proto\x12\x1c\x63om.hedera.hapi.block.stream\x1a+block/stream/signed_record_file_proof.proto\x1a\x1e\x62lock/stream/state_proof.proto\x1a)block/stream/tss_signed_block_proof.proto\"\x95\x02\n\nBlockProof\x12\r\n\x05\x62lock\x18\x01 \x01(\x04\x12O\n\x12signed_block_proof\x18\x02 \x01(\x0b\x32\x31.com.hedera.hapi.block.stream.TssSignedBlockProofH\x00\x12\x45\n\x11\x62lock_state_proof\x18\x03 \x01(\x0b\x32(.com.hedera.hapi.block.stream.StateProofH\x00\x12W\n\x18signed_record_file_proof\x18\x04 \x01(\x0b\x32\x33.com.hedera.hapi.block.stream.SignedRecordFileProofH\x00\x42\x07\n\x05proofB\'\n#com.hedera.hapi.block.stream.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          BlockProof = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.BlockProof").msgclass
        end
      end
    end
  end
end
