# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/block.proto

require 'google/protobuf'

require 'hiero/proto/block/stream/block_item_pb'


descriptor_data = "\n\x18\x62lock/stream/block.proto\x12\x1c\x63om.hedera.hapi.block.stream\x1a\x1d\x62lock/stream/block_item.proto\"?\n\x05\x42lock\x12\x36\n\x05items\x18\x01 \x03(\x0b\x32\'.com.hedera.hapi.block.stream.BlockItemB\'\n#com.hedera.hapi.block.stream.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          Block = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.Block").msgclass
        end
      end
    end
  end
end
