# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/record_file_item.proto

require 'google/protobuf'

require 'hiero/proto/services/timestamp_pb'
require 'hiero/proto/streams/sidecar_file_pb'
require 'hiero/proto/streams/record_stream_file_pb'
require 'hiero/proto/services/transaction_record_pb'
require 'hiero/proto/services/transaction_contents_pb'


descriptor_data = "\n#block/stream/record_file_item.proto\x12\x1c\x63om.hedera.hapi.block.stream\x1a\x18services/timestamp.proto\x1a\x1astreams/sidecar_file.proto\x1a streams/record_stream_file.proto\x1a!services/transaction_record.proto\x1a#services/transaction_contents.proto\"\xd0\x01\n\x0eRecordFileItem\x12\'\n\rcreation_time\x18\x01 \x01(\x0b\x32\x10.proto.Timestamp\x12\x35\n\x14record_file_contents\x18\x02 \x01(\x0b\x32\x17.proto.RecordStreamFile\x12\x31\n\x15sidecar_file_contents\x18\x03 \x03(\x0b\x32\x12.proto.SidecarFile\x12+\n\namendments\x18\x04 \x03(\x0b\x32\x17.proto.RecordStreamItemB\'\n#com.hedera.hapi.block.stream.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          RecordFileItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.RecordFileItem").msgclass
        end
      end
    end
  end
end
