# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/signed_record_file_proof.proto

require 'google/protobuf'


descriptor_data = "\n+block/stream/signed_record_file_proof.proto\x12\x1c\x63om.hedera.hapi.block.stream\"{\n\x15SignedRecordFileProof\x12\x0f\n\x07version\x18\x01 \x01(\r\x12Q\n\x16record_file_signatures\x18\x02 \x03(\x0b\x32\x31.com.hedera.hapi.block.stream.RecordFileSignature\"@\n\x13RecordFileSignature\x12\x18\n\x10signatures_bytes\x18\x01 \x01(\x0c\x12\x0f\n\x07node_id\x18\x02 \x01(\x04\x42\'\n#com.hedera.hapi.block.stream.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          SignedRecordFileProof = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.SignedRecordFileProof").msgclass
          RecordFileSignature = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.RecordFileSignature").msgclass
        end
      end
    end
  end
end
