# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/state_proof.proto

require 'google/protobuf'

require 'hiero/proto/services/timestamp_pb'
require 'hiero/proto/block/stream/record_file_item_pb'
require 'hiero/proto/block/stream/tss_signed_block_proof_pb'


descriptor_data = "\n\x1e\x62lock/stream/state_proof.proto\x12\x1c\x63om.hedera.hapi.block.stream\x1a\x18services/timestamp.proto\x1a#block/stream/record_file_item.proto\x1a)block/stream/tss_signed_block_proof.proto\"\x9f\x01\n\nStateProof\x12\x37\n\x05paths\x18\x01 \x03(\x0b\x32(.com.hedera.hapi.block.stream.MerklePath\x12O\n\x12signed_block_proof\x18\x02 \x01(\x0b\x32\x31.com.hedera.hapi.block.stream.TssSignedBlockProofH\x00\x42\x07\n\x05proof\"\xcd\x01\n\nMerklePath\x12;\n\x08siblings\x18\x01 \x03(\x0b\x32).com.hedera.hapi.block.stream.SiblingNode\x12\x17\n\x0fnext_path_index\x18\x02 \x01(\r\x12\x0e\n\x04hash\x18\x03 \x01(\x0cH\x00\x12\x19\n\x0fstate_item_leaf\x18\x04 \x01(\x0cH\x00\x12\x19\n\x0f\x62lock_item_leaf\x18\x05 \x01(\x0cH\x00\x12\x18\n\x0etimestamp_leaf\x18\x06 \x01(\x0cH\x00\x42\t\n\x07\x63ontent\",\n\x0bSiblingNode\x12\x0f\n\x07is_left\x18\x01 \x01(\x08\x12\x0c\n\x04hash\x18\x02 \x01(\x0c\";\n\x11MerkleSiblingHash\x12\x10\n\x08is_first\x18\x01 \x01(\x08\x12\x14\n\x0csibling_hash\x18\x02 \x01(\x0c\x42\'\n#com.hedera.hapi.block.stream.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          StateProof = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.StateProof").msgclass
          MerklePath = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.MerklePath").msgclass
          SiblingNode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.SiblingNode").msgclass
          MerkleSiblingHash = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.MerkleSiblingHash").msgclass
        end
      end
    end
  end
end
