# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block/stream/tss_signed_block_proof.proto

require 'google/protobuf'


descriptor_data = "\n)block/stream/tss_signed_block_proof.proto\x12\x1c\x63om.hedera.hapi.block.stream\".\n\x13TssSignedBlockProof\x12\x17\n\x0f\x62lock_signature\x18\x01 \x01(\x0c\x42\'\n#com.hedera.hapi.block.stream.protocP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Block
        module Stream
          TssSignedBlockProof = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.block.stream.TssSignedBlockProof").msgclass
        end
      end
    end
  end
end
