# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/message/gossip_ping.proto

require 'google/protobuf'


descriptor_data = "\n\"platform/message/gossip_ping.proto\x12 com.hedera.hapi.platform.message\"#\n\nGossipPing\x12\x15\n\rcorrelationId\x18\x02 \x01(\x03\x42+\n\'com.hedera.hapi.platform.message.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Platform
        module Message
          GossipPing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.platform.message.GossipPing").msgclass
        end
      end
    end
  end
end
