# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/message/gossip_sync_data.proto

require 'google/protobuf'


descriptor_data = "\n\'platform/message/gossip_sync_data.proto\x12 com.hedera.hapi.platform.message\"e\n\x11GossipEventWindow\x12\x1c\n\x14latestConsensusRound\x18\x01 \x01(\x03\x12\x18\n\x10\x61ncientThreshold\x18\x02 \x01(\x03\x12\x18\n\x10\x65xpiredThreshold\x18\x03 \x01(\x03\"~\n\x0eGossipSyncData\x12\x43\n\x06window\x18\x01 \x01(\x0b\x32\x33.com.hedera.hapi.platform.message.GossipEventWindow\x12\x0c\n\x04tips\x18\x02 \x03(\x0c\x12\x19\n\x11skipSendingEvents\x18\x03 \x01(\x08\x42+\n\'com.hedera.hapi.platform.message.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Platform
        module Message
          GossipEventWindow = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.platform.message.GossipEventWindow").msgclass
          GossipSyncData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.platform.message.GossipSyncData").msgclass
        end
      end
    end
  end
end
