# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/event/event_core.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/timestamp_pb'


descriptor_data = "\n\x1fplatform/event/event_core.proto\x12\x1e\x63om.hedera.hapi.platform.event\x1a\x1aservices/basic_types.proto\x1a\x18services/timestamp.proto\"{\n\tEventCore\x12\x17\n\x0f\x63reator_node_id\x18\x01 \x01(\x03\x12\x13\n\x0b\x62irth_round\x18\x02 \x01(\x03\x12&\n\x0ctime_created\x18\x03 \x01(\x0b\x32\x10.proto.Timestamp\x12\x0c\n\x04\x63oin\x18\x05 \x01(\x03J\x04\x08\x04\x10\x05J\x04\x08\x11\x10\x12\x42)\n%com.hedera.hapi.platform.event.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Platform
        module Event
          EventCore = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.platform.event.EventCore").msgclass
        end
      end
    end
  end
end
