# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/event/event_descriptor.proto

require 'google/protobuf'


descriptor_data = "\n%platform/event/event_descriptor.proto\x12\x1e\x63om.hedera.hapi.platform.event\"S\n\x0f\x45ventDescriptor\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\x12\x17\n\x0f\x63reator_node_id\x18\x02 \x01(\x03\x12\x13\n\x0b\x62irth_round\x18\x03 \x01(\x03J\x04\x08\x11\x10\x12\x42)\n%com.hedera.hapi.platform.event.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Platform
        module Event
          EventDescriptor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.platform.event.EventDescriptor").msgclass
        end
      end
    end
  end
end
