# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/event/event_consensus_data.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/platform/event/event_descriptor_pb'
require 'hiero/proto/services/timestamp_pb'


descriptor_data = "\n)platform/event/event_consensus_data.proto\x12\x1e\x63om.hedera.hapi.platform.event\x1a\x1aservices/basic_types.proto\x1a%platform/event/event_descriptor.proto\x1a\x18services/timestamp.proto\"\\\n\x12\x45ventConsensusData\x12-\n\x13\x63onsensus_timestamp\x18\x01 \x01(\x0b\x32\x10.proto.Timestamp\x12\x17\n\x0f\x63onsensus_order\x18\x02 \x01(\x04\x42)\n%com.hedera.hapi.platform.event.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Platform
        module Event
          EventConsensusData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.platform.event.EventConsensusData").msgclass
        end
      end
    end
  end
end
