# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/event/gossip_event.proto

require 'google/protobuf'

require 'hiero/proto/platform/event/event_core_pb'
require 'hiero/proto/platform/event/event_descriptor_pb'


descriptor_data = "\n!platform/event/gossip_event.proto\x12\x1e\x63om.hedera.hapi.platform.event\x1a\x1fplatform/event/event_core.proto\x1a%platform/event/event_descriptor.proto\"\xbd\x01\n\x0bGossipEvent\x12=\n\nevent_core\x18\x01 \x01(\x0b\x32).com.hedera.hapi.platform.event.EventCore\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\x14\n\x0ctransactions\x18\x04 \x03(\x0c\x12@\n\x07parents\x18\x05 \x03(\x0b\x32/.com.hedera.hapi.platform.event.EventDescriptorJ\x04\x08\x03\x10\x04\x42)\n%com.hedera.hapi.platform.event.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Platform
        module Event
          GossipEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.platform.event.GossipEvent").msgclass
        end
      end
    end
  end
end
