# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/event/state_signature_transaction.proto

require 'google/protobuf'


descriptor_data = "\n0platform/event/state_signature_transaction.proto\x12\x1e\x63om.hedera.hapi.platform.event\"K\n\x19StateSignatureTransaction\x12\r\n\x05round\x18\x01 \x01(\x03\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\x0c\n\x04hash\x18\x03 \x01(\x0c\x42)\n%com.hedera.hapi.platform.event.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Platform
        module Event
          StateSignatureTransaction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.platform.event.StateSignatureTransaction").msgclass
        end
      end
    end
  end
end
