# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/roster/ledger_id.proto

require 'google/protobuf'


descriptor_data = "\n%services/state/roster/ledger_id.proto\x12!com.hedera.hapi.node.state.roster\"\x96\x01\n\x08LedgerId\x12\x11\n\tledger_id\x18\x01 \x01(\x0c\x12\r\n\x05round\x18\x02 \x01(\x04\x12\x18\n\x10ledger_signature\x18\x03 \x01(\x0c\x12N\n\x11roster_signatures\x18\x04 \x01(\x0b\x32\x33.com.hedera.hapi.node.state.roster.RosterSignatures\"r\n\x10RosterSignatures\x12\x13\n\x0broster_hash\x18\x01 \x01(\x0c\x12I\n\x0fnode_signatures\x18\x02 \x03(\x0b\x32\x30.com.hedera.hapi.node.state.roster.NodeSignature\"8\n\rNodeSignature\x12\x0f\n\x07node_id\x18\x01 \x01(\x04\x12\x16\n\x0enode_signature\x18\x02 \x01(\x0c\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module State
          module Roster
            LedgerId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.roster.LedgerId").msgclass
            RosterSignatures = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.roster.RosterSignatures").msgclass
            NodeSignature = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.roster.NodeSignature").msgclass
          end
        end
      end
    end
  end
end
