# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/roster/roster.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\"services/state/roster/roster.proto\x12!com.hedera.hapi.node.state.roster\x1a\x1aservices/basic_types.proto\"P\n\x06Roster\x12\x46\n\x0eroster_entries\x18\x01 \x03(\x0b\x32..com.hedera.hapi.node.state.roster.RosterEntry\"\x84\x01\n\x0bRosterEntry\x12\x0f\n\x07node_id\x18\x01 \x01(\x04\x12\x0e\n\x06weight\x18\x02 \x01(\x04\x12\x1d\n\x15gossip_ca_certificate\x18\x03 \x01(\x0c\x12/\n\x0fgossip_endpoint\x18\x05 \x03(\x0b\x32\x16.proto.ServiceEndpointJ\x04\x08\x04\x10\x05\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module State
          module Roster
            Roster = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.roster.Roster").msgclass
            RosterEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.roster.RosterEntry").msgclass
          end
        end
      end
    end
  end
end
