# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/roster/roster_state.proto

require 'google/protobuf'


descriptor_data = "\n(services/state/roster/roster_state.proto\x12!com.hedera.hapi.node.state.roster\"\x9c\x01\n\x0bRosterState\x12\x1d\n\x15\x63\x61ndidate_roster_hash\x18\x01 \x01(\x0c\x12N\n\x12round_roster_pairs\x18\x02 \x03(\x0b\x32\x32.com.hedera.hapi.node.state.roster.RoundRosterPair\x12\x1e\n\x16transplant_in_progress\x18\x03 \x01(\x08\"C\n\x0fRoundRosterPair\x12\x14\n\x0cround_number\x18\x01 \x01(\x04\x12\x1a\n\x12\x61\x63tive_roster_hash\x18\x02 \x01(\x0c\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module State
          module Roster
            RosterState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.roster.RosterState").msgclass
            RoundRosterPair = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.roster.RoundRosterPair").msgclass
          end
        end
      end
    end
  end
end
