# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/auxiliary/hints/crs_publication.proto

require 'google/protobuf'


descriptor_data = "\n.services/auxiliary/hints/crs_publication.proto\x12(com.hedera.hapi.services.auxiliary.hints\"?\n\x1d\x43rsPublicationTransactionBody\x12\x0f\n\x07new_crs\x18\x01 \x01(\x0c\x12\r\n\x05proof\x18\x02 \x01(\x0c\x42\x33\n/com.hedera.hapi.services.auxiliary.hints.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Services
        module Auxiliary
          module Hints
            CrsPublicationTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.services.auxiliary.hints.CrsPublicationTransactionBody").msgclass
          end
        end
      end
    end
  end
end
