# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/auxiliary/hints/hints_preprocessing_vote.proto

require 'google/protobuf'

require 'hiero/proto/services/state/hints/hints_types_pb'


descriptor_data = "\n7services/auxiliary/hints/hints_preprocessing_vote.proto\x12(com.hedera.hapi.services.auxiliary.hints\x1a&services/state/hints/hints_types.proto\"\x83\x01\n%HintsPreprocessingVoteTransactionBody\x12\x17\n\x0f\x63onstruction_id\x18\x01 \x01(\x04\x12\x41\n\x04vote\x18\x02 \x01(\x0b\x32\x33.com.hedera.hapi.node.state.hints.PreprocessingVoteB3\n/com.hedera.hapi.services.auxiliary.hints.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Services
        module Auxiliary
          module Hints
            HintsPreprocessingVoteTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.services.auxiliary.hints.HintsPreprocessingVoteTransactionBody").msgclass
          end
        end
      end
    end
  end
end
