# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/auxiliary/hints/hints_partial_signature.proto

require 'google/protobuf'


descriptor_data = "\n6services/auxiliary/hints/hints_partial_signature.proto\x12(com.hedera.hapi.services.auxiliary.hints\"k\n$HintsPartialSignatureTransactionBody\x12\x17\n\x0f\x63onstruction_id\x18\x01 \x01(\x04\x12\x0f\n\x07message\x18\x02 \x01(\x0c\x12\x19\n\x11partial_signature\x18\x03 \x01(\x0c\x42\x33\n/com.hedera.hapi.services.auxiliary.hints.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Services
        module Auxiliary
          module Hints
            HintsPartialSignatureTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.services.auxiliary.hints.HintsPartialSignatureTransactionBody").msgclass
          end
        end
      end
    end
  end
end
