# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/auxiliary/hints/hints_key_publication.proto

require 'google/protobuf'


descriptor_data = "\n4services/auxiliary/hints/hints_key_publication.proto\x12(com.hedera.hapi.services.auxiliary.hints\"^\n\"HintsKeyPublicationTransactionBody\x12\x10\n\x08party_id\x18\x01 \x01(\r\x12\x13\n\x0bnum_parties\x18\x02 \x01(\r\x12\x11\n\thints_key\x18\x03 \x01(\x0c\x42\x33\n/com.hedera.hapi.services.auxiliary.hints.legacyP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Services
        module Auxiliary
          module Hints
            HintsKeyPublicationTransactionBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.services.auxiliary.hints.HintsKeyPublicationTransactionBody").msgclass
          end
        end
      end
    end
  end
end
