# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/congestion/congestion_level_starts.proto

require 'google/protobuf'

require 'hiero/proto/services/timestamp_pb'


descriptor_data = "\n7services/state/congestion/congestion_level_starts.proto\x12\x05proto\x1a\x18services/timestamp.proto\"s\n\x15\x43ongestionLevelStarts\x12.\n\x14generic_level_starts\x18\x01 \x03(\x0b\x32\x10.proto.Timestamp\x12*\n\x10gas_level_starts\x18\x02 \x03(\x0b\x32\x10.proto.TimestampB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  CongestionLevelStarts = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CongestionLevelStarts").msgclass
end
