# frozen_string_literal: true
#
# Generated by bin/generate_protos. Do not edit.

require "hiero/proto/platform/event/event_consensus_data_pb"
require "hiero/proto/platform/event/event_core_pb"
require "hiero/proto/platform/event/event_descriptor_pb"
require "hiero/proto/platform/event/gossip_event_pb"
require "hiero/proto/platform/event/state_signature_transaction_pb"
require "hiero/proto/platform/message/gossip_known_tips_pb"
require "hiero/proto/platform/message/gossip_ping_pb"
require "hiero/proto/platform/message/gossip_sync_data_pb"
require "hiero/proto/platform/state/platform_state_pb"
require "hiero/proto/platform/state/virtual_map_state_pb"
