# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/recordcache/recordcache.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/transaction_record_pb'
require 'hiero/proto/services/response_code_pb'


descriptor_data = "\n,services/state/recordcache/recordcache.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\x1a!services/transaction_record.proto\x1a\x1cservices/response_code.proto\"\x8b\x01\n\x16TransactionRecordEntry\x12\x0f\n\x07node_id\x18\x01 \x01(\x03\x12*\n\x10payer_account_id\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12\x34\n\x12transaction_record\x18\x03 \x01(\x0b\x32\x18.proto.TransactionRecord\"\x81\x01\n\x17TransactionReceiptEntry\x12\x0f\n\x07node_id\x18\x01 \x01(\x04\x12,\n\x0etransaction_id\x18\x02 \x01(\x0b\x32\x14.proto.TransactionID\x12\'\n\x06status\x18\x03 \x01(\x0e\x32\x17.proto.ResponseCodeEnum\"L\n\x19TransactionReceiptEntries\x12/\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1e.proto.TransactionReceiptEntryB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  TransactionRecordEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TransactionRecordEntry").msgclass
  TransactionReceiptEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TransactionReceiptEntry").msgclass
  TransactionReceiptEntries = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TransactionReceiptEntries").msgclass
end
