# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/file/file.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'


descriptor_data = "\n\x1eservices/state/file/file.proto\x12\x05proto\x1a\x1aservices/basic_types.proto\"\xbd\x01\n\x04\x46ile\x12\x1e\n\x07\x66ile_id\x18\x01 \x01(\x0b\x32\r.proto.FileID\x12\x19\n\x11\x65xpiration_second\x18\x02 \x01(\x03\x12\x1c\n\x04keys\x18\x03 \x01(\x0b\x32\x0e.proto.KeyList\x12\x10\n\x08\x63ontents\x18\x04 \x01(\x0c\x12\x0c\n\x04memo\x18\x05 \x01(\t\x12\x0f\n\x07\x64\x65leted\x18\x06 \x01(\x08\x12+\n#pre_system_delete_expiration_second\x18\x07 \x01(\x03\x42&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  File = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.File").msgclass
end
