# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/state/addressbook/registered_node.proto

require 'google/protobuf'

require 'hiero/proto/services/basic_types_pb'
require 'hiero/proto/services/registered_service_endpoint_pb'


descriptor_data = "\n0services/state/addressbook/registered_node.proto\x12&com.hedera.hapi.node.state.addressbook\x1a\x1aservices/basic_types.proto\x1a*services/registered_service_endpoint.proto\"\xb7\x01\n\x0eRegisteredNode\x12\x1a\n\x12registered_node_id\x18\x01 \x01(\x04\x12\x1d\n\tadmin_key\x18\x02 \x01(\x0b\x32\n.proto.Key\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12U\n\x10service_endpoint\x18\x04 \x03(\x0b\x32;.com.hedera.hapi.node.addressbook.RegisteredServiceEndpointB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Hedera
    module Hapi
      module Node
        module State
          module Addressbook
            RegisteredNode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hedera.hapi.node.state.addressbook.RegisteredNode").msgclass
          end
        end
      end
    end
  end
end
